const ALL_TRANSLATIONS = {
    "de": {
        "pageTitle": "Interaktiver Vermögensplaner",
        "languageSelector": "Sprache",
        "navbarBrand": "Vermögensplaner",
        "darkModeLabel": "Dunkelmodus",
        "importButton": "Importieren",
        "exportButton": "Exportieren",
        "clearButton": "Löschen",
        "settingsTitle": "Einstellungen",
        "inflationLabel": "Inflation (%)",
        "financialDataTitle": "Finanzdaten",
        "assetsAccordionButton": "Vermögenswerte",
        "newAssetButton": "Neue Anlageklasse",
        "liabilitiesAccordionButton": "Verbindlichkeiten",
        "newLiabilityButton": "Neue Haftungsklasse",
        "incomeAccordionButton": "Einkommen",
        "newIncomeButton": "Neue Einkommenskategorie",
        "expensesAccordionButton": "Ausgaben",
        "newExpenseButton": "Neue Ausgabenkategorie",
        "savingsAllocationAccordionButton": "Sparzuweisung",
        "newAllocationPeriodButton": "Neuer Zuweisungszeitraum",
        "retirementPlanningAccordionButton": "Ruhestandsplanung",
        "currentAgeLabel": "Aktuelles Alter",
        "retirementAgeLabel": "Rentenalter",
        "monthlyPensionLabel": "Monatliche Rente (netto)",
        "withdrawalRateLabel": "Entnahmerate (%)",
        "runSimulationButton": "Simulation durchführen",
        "resultsTitle": "Ergebnisse",
        "helpModalTitle": "Hilfe",
        "helpModalWelcome": "Willkommen beim Interaktiven Vermögensplaner!",
        "helpModalIntro": "Dieses kostenlose und quelloffene Tool hilft Ihnen bei der Planung und Visualisierung Ihrer finanziellen Zukunft.",
        "helpModalHowToUse": "Wie zu verwenden:",
        "helpModalStep1": "<strong>Einstellungen:</strong> Passen Sie die Inflationsrate nach Wunsch an.",
        "helpModalStep2": "<strong>Finanzdaten:</strong> Geben Sie Ihre Vermögenswerte, Verbindlichkeiten, Einnahmen und Ausgaben ein.",
        "helpModalStep3": "<strong>Sparzuweisung:</strong> Legen Sie fest, wie Ihre Ersparnisse über verschiedene Zeiträume investiert werden.",
        "helpModalStep4": "<strong>Ruhestandsplanung:</strong> Geben Sie Ihr aktuelles Alter, das gewünschte Rentenalter und die erwartete Rente ein.",
        "helpModalStep5": "<strong>Simulation durchführen:</strong> Klicken Sie auf die Schaltfläche, um die Entwicklung Ihres Vermögens zu sehen.",
        "helpModalResultsInfo": "Die Ergebnisse werden in einem Diagramm und einer Tabelle angezeigt.",
        "helpModalButtonsInfo": "Mit den Schaltflächen oben rechts können Sie alle Ihre Daten importieren, exportieren oder löschen.",
        "helpModalPrivacy": "Datenschutz zuerst: Ihre Daten werden niemals in irgendeiner Form gespeichert oder weitergegeben.",
        "helpModalSourceCode": "Quellcode verfügbar unter: <a href=\"https://github.com/skapebolt/wealth-planner-tool\">https://github.com/skapebolt/wealth-planner-tool</a>",
        "nameLabel": "Name",
        "valueLabel": "Wert",
        "returnLabel": "Rendite (%)",
        "taxLabel": "Steuer (%)",
        "startLabel": "Start",
        "endLabel": "Ende",
        "withdrawalOrderLabel": "Reihenfolge",
        "frequencyLabel": "Häufigkeit",
        "indexedLabel": "Indexiert",
        "monthlyOption": "Monatlich",
        "yearlyOption": "Jährlich",
        "deleteAssetCategoryLabel": "Anlagekategorie löschen",
        "deleteLiabilityCategoryLabel": "Haftungskategorie löschen",
        "deleteIncomeCategoryLabel": "Einkommenskategorie löschen",
        "deleteExpenseCategoryLabel": "Ausgabenkategorie löschen",
        "deleteAllocationPeriodLabel": "Zuweisungszeitraum löschen",
        "startYearLabel": "Startjahr",
        "clearDataConfirmation": "Sind Sie sicher, dass Sie alle Daten löschen möchten?",
        "earlyRetirementMessage": "Sie können möglicherweise im Jahr <strong>{year}</strong> im Alter von <strong>{age}</strong> mit einem Nettovermögen von <strong>{netWorth}</strong> in den Vorruhestand gehen!",
        "pensionWithdrawalMessage": "Ihre erste jährliche Auszahlung bei Erreichen des Rentenalters würde <strong>{amount}</strong> ({rate}% von {netWorth}) betragen, oder <strong>{monthly}</strong> pro Monat.",
        "netWorthLabel": "Nettovermögen",
        "yearHeader": "Jahr",
        "ageHeader": "Alter",
        "netIncomeHeader": "Nettoeinkommen",
        "expensesHeader": "Ausgaben",
        "savingsCapacityHeader": "Sparkapazität",
        "savingsRateHeader": "Sparquote",
        "netWorthHeader": "Nettovermögen",
        "assetHeader": "{asset} (Vermögenswert)",
        "liabilityHeader": "{liability} (Verbindlichkeit)",
        "ownHome": "Eigenheim",
        "stocks": "Aktien",
        "savingsAccount": "Sparkonto",
        "mortgage": "Hypothek",
        "salary": "Gehalt",
        "livingExpenses": "Lebenshaltungskosten",
        "mortgageRepayment": "Hypothekenrückzahlung",
        "languageChangeWarning": "Beim Ändern der Sprache werden alle Ihre Daten zurückgesetzt. Möchten Sie fortfahren?",
        "inflationTooltip": "Die durchschnittliche jährliche Preissteigerung. Dies wird verwendet, um den zukünftigen Wert des Geldes zu berechnen.",
        "currentAgeTooltip": "Ihr aktuelles Alter in Jahren.",
        "retirementAgeTooltip": "Das Alter, in dem Sie in Rente gehen möchten.",
        "monthlyPensionTooltip": "Die geschätzte monatliche Nettorente, die Sie von der Regierung erhalten werden.",
        "withdrawalRateTooltip": "Der Prozentsatz Ihres Gesamtvermögens, den Sie jährlich nach der Pensionierung abheben möchten (z.B. die 4%-Regel).",
        "assetNameTooltip": "Ein eindeutiger Name für diese Kategorie.",
        "assetValueTooltip": "Der aktuelle Wert in Ihrer Währung.",
        "assetReturnTooltip": "Die erwartete jährliche Rendite auf dieses Vermögen nach Kosten.",
        "assetTaxTooltip": "Die jährliche Steuer auf die Rendite oder den Kapitalgewinn.",
        "assetStartYearTooltip": "Das Jahr, in dem diese Kategorie aktiv wird.",
        "assetEndYearTooltip": "Das Jahr, in dem diese Kategorie endet. Leer lassen, falls nicht zutreffend.",
        "assetWithdrawalOrderTooltip": "Die Reihenfolge der Auszahlung im Falle eines Defizits oder nach der Pensionierung (1 = zuerst, 99 = zuletzt).",
        "liabilityNameTooltip": "Ein eindeutiger Name für diese Kategorie.",
        "liabilityValueTooltip": "Der aktuelle Wert in Ihrer Währung.",
        "liabilityStartYearTooltip": "Das Jahr, in dem diese Kategorie aktiv wird.",
        "liabilityEndYearTooltip": "Das Jahr, in dem diese Kategorie endet. Leer lassen, falls nicht zutreffend.",
        "incomeNameTooltip": "Ein eindeutiger Name für diese Kategorie.",
        "incomeValueTooltip": "Der aktuelle Wert in Ihrer Währung.",
        "incomeFrequencyTooltip": "Wie oft dieses Einkommen anfällt.",
        "incomeIndexedTooltip": "Aktivieren Sie dieses Kontrollkästchen, wenn dieser Betrag jährlich mit der Inflation steigen soll.",
        "incomeStartYearTooltip": "Das Jahr, in dem diese Kategorie aktiv wird.",
        "incomeEndYearTooltip": "Das Jahr, in dem diese Kategorie endet. Leer lassen, falls nicht zutreffend.",
        "expenseNameTooltip": "Ein eindeutiger Name für diese Kategorie.",
        "expenseValueTooltip": "Der aktuelle Wert in Ihrer Währung.",
        "expenseFrequencyTooltip": "Wie oft diese Ausgabe anfällt.",
        "expenseIndexedTooltip": "Aktivieren Sie dieses Kontrollkästchen, wenn dieser Betrag jährlich mit der Inflation steigen soll.",
        "expenseStartYearTooltip": "Das Jahr, in dem diese Kategorie aktiv wird.",
        "expenseEndYearTooltip": "Das Jahr, in dem diese Kategorie endet. Leer lassen, falls nicht zutreffend.",
        "languageAlreadySelected": "Diese Sprache ist bereits ausgewählt.",
        "notificationTitle": "Benachrichtigung",
        "endYearBeforeStartYearError": "Endjahr kann nicht vor Startjahr liegen.",
        "retirementAgeBeforeCurrentAgeError": "Rentenalter kann nicht kleiner sein als aktuelles Alter.",
        "autoRebalanceLabel": "Automatisches Auswuchten",
        "autoRebalanceTooltip": "Wenn diese Option aktiviert ist, werden die prozentualen Anteile der Vermögenswerte während der gesamten Simulation durch automatisches Auswuchten beibehalten."
    },
    "en": {
        "pageTitle": "Interactive Wealth Planner",
        "languageSelector": "Language",
        "navbarBrand": "Wealth Planner",
        "darkModeLabel": "Dark mode",
        "importButton": "Import",
        "exportButton": "Export",
        "clearButton": "Clear",
        "settingsTitle": "Settings",
        "inflationLabel": "Inflation (%)",
        "financialDataTitle": "Financial Data",
        "assetsAccordionButton": "Assets",
        "newAssetButton": "New Asset Class",
        "liabilitiesAccordionButton": "Liabilities",
        "newLiabilityButton": "New Liability Class",
        "incomeAccordionButton": "Income",
        "newIncomeButton": "New Income Category",
        "expensesAccordionButton": "Expenses",
        "newExpenseButton": "New Expense Category",
        "savingsAllocationAccordionButton": "Savings Allocation",
        "newAllocationPeriodButton": "New Allocation Period",
        "retirementPlanningAccordionButton": "Retirement Planning",
        "currentAgeLabel": "Current Age",
        "retirementAgeLabel": "Retirement Age",
        "monthlyPensionLabel": "Monthly Pension (net)",
        "withdrawalRateLabel": "Withdrawal Rate (%)",
        "runSimulationButton": "Run Simulation",
        "resultsTitle": "Results",
        "helpModalTitle": "Help",
        "helpModalWelcome": "Welcome to the Interactive Wealth Planner!",
        "helpModalIntro": "This free and open source tool helps you plan and visualize your financial future.",
        "helpModalHowToUse": "How to use:",
        "helpModalStep1": "<strong>Settings:</strong> Adjust the inflation rate as desired.",
        "helpModalStep2": "<strong>Financial Data:</strong> Fill in your assets, liabilities, income, and expenses.",
        "helpModalStep3": "<strong>Savings Allocation:</strong> Determine how your savings are invested over different periods.",
        "helpModalStep4": "<strong>Retirement Planning:</strong> Fill in your current age, desired retirement age, and expected pension.",
        "helpModalStep5": "<strong>Run Simulation:</strong> Click the button to see the evolution of your wealth.",
        "helpModalResultsInfo": "The results are displayed in a chart and a table.",
        "helpModalButtonsInfo": "With the buttons at the top right, you can import, export, or clear all your data.",
        "helpModalPrivacy": "Privacy first: Your data will never be stored or shared in any way, shape or form.",
        "helpModalSourceCode": "Source code availaible at: <a href=\"https://github.com/skapebolt/wealth-planner-tool\">https://github.com/skapebolt/wealth-planner-tool</a>",
        "nameLabel": "Name",
        "valueLabel": "Value",
        "returnLabel": "Return (%)",
        "taxLabel": "Tax (%)",
        "startLabel": "Start",
        "endLabel": "End",
        "withdrawalOrderLabel": "Order",
        "frequencyLabel": "Frequency",
        "indexedLabel": "Indexed",
        "monthlyOption": "Monthly",
        "yearlyOption": "Yearly",
        "deleteAssetCategoryLabel": "Delete asset category",
        "deleteLiabilityCategoryLabel": "Delete liability category",
        "deleteIncomeCategoryLabel": "Delete income category",
        "deleteExpenseCategoryLabel": "Delete expense category",
        "deleteAllocationPeriodLabel": "Delete allocation period",
        "startYearLabel": "Start Year",
        "clearDataConfirmation": "Are you sure you want to clear all data?",
        "earlyRetirementMessage": "You may be able to retire early in <strong>{year}</strong> at the age of <strong>{age}</strong> with a net worth of <strong>{netWorth}</strong>!",
        "pensionWithdrawalMessage": "Your first annual withdrawal upon reaching retirement age would be <strong>{amount}</strong> ({rate}% of {netWorth}), or <strong>{monthly}</strong> per month.",
        "netWorthLabel": "Net Worth",
        "yearHeader": "Year",
        "ageHeader": "Age",
        "netIncomeHeader": "Net Income",
        "expensesHeader": "Expenses",
        "savingsCapacityHeader": "Savings Capacity",
        "savingsRateHeader": "Savings Rate",
        "netWorthHeader": "Net Worth",
        "assetHeader": "{asset} (Asset)",
        "liabilityHeader": "{liability} (Liability)",
        "ownHome": "Own Home",
        "stocks": "Stocks",
        "savingsAccount": "Savings Account",
        "mortgage": "Mortgage",
        "salary": "Salary",
        "livingExpenses": "Living Expenses",
        "mortgageRepayment": "Mortgage Repayment",
        "languageChangeWarning": "Changing the language will reset all your data. Do you want to proceed?",
        "inflationTooltip": "The average annual increase in prices. This is used to calculate the future value of money.",
        "currentAgeTooltip": "Your current age in years.",
        "retirementAgeTooltip": "The age at which you plan to retire.",
        "monthlyPensionTooltip": "The estimated net monthly pension you will receive from the government.",
        "withdrawalRateTooltip": "The percentage of your total assets that you plan to withdraw annually after retirement (e.g., the 4% rule).",
        "assetNameTooltip": "A unique name for this category.",
        "assetValueTooltip": "The current value in your currency.",
        "assetReturnTooltip": "The expected annual return on this asset, after costs.",
        "assetTaxTooltip": "The annual tax on the return or capital gain.",
        "assetStartYearTooltip": "The year this category becomes active.",
        "assetEndYearTooltip": "The year this category stops. Leave empty if not applicable.",
        "assetWithdrawalOrderTooltip": "The withdrawal order in case of a deficit or after retirement (1 = first, 99 = last).",
        "liabilityNameTooltip": "A unique name for this category.",
        "liabilityValueTooltip": "The current value in your currency.",
        "liabilityStartYearTooltip": "The year this category becomes active.",
        "liabilityEndYearTooltip": "The year this category stops. Leave empty if not applicable.",
        "incomeNameTooltip": "A unique name for this category.",
        "incomeValueTooltip": "The current value in your currency.",
        "incomeFrequencyTooltip": "How often this income occurs.",
        "incomeIndexedTooltip": "Check if this amount should increase annually with inflation.",
        "incomeStartYearTooltip": "The year this category becomes active.",
        "incomeEndYearTooltip": "The year this category stops. Leave empty if not applicable.",
        "expenseNameTooltip": "A unique name for this category.",
        "expenseValueTooltip": "The current value in your currency.",
        "expenseFrequencyTooltip": "How often this expense occurs.",
        "expenseIndexedTooltip": "Check if this amount should increase annually with inflation.",
        "expenseStartYearTooltip": "The year this category becomes active.",
        "expenseEndYearTooltip": "The year this category stops. Leave empty if not applicable.",
        "languageAlreadySelected": "This language is already selected.",
        "notificationTitle": "Notification",
        "endYearBeforeStartYearError": "End year cannot be before start year.",
        "retirementAgeBeforeCurrentAgeError": "Retirement age cannot be less than current age.",
        "autoRebalanceLabel": "Automatic rebalance",
        "autoRebalanceTooltip": "If checked, the asset allocation percentages will be maintained throughout the simulation by automatically rebalancing the portfolio."
    },
    "es": {
        "pageTitle": "Planificador de Riqueza Interactivo",
        "languageSelector": "Idioma",
        "navbarBrand": "Planificador de Riqueza",
        "darkModeLabel": "Modo oscuro",
        "importButton": "Importar",
        "exportButton": "Exportar",
        "clearButton": "Limpiar",
        "settingsTitle": "Configuración",
        "inflationLabel": "Inflación (%)",
        "financialDataTitle": "Datos Financieros",
        "assetsAccordionButton": "Activos",
        "newAssetButton": "Nueva clase de activos",
        "liabilitiesAccordionButton": "Pasivos",
        "newLiabilityButton": "Nueva clase de pasivos",
        "incomeAccordionButton": "Ingresos",
        "newIncomeButton": "Nueva categoría de ingresos",
        "expensesAccordionButton": "Gastos",
        "newExpenseButton": "Nueva categoría de gastos",
        "savingsAllocationAccordionButton": "Asignación de Ahorros",
        "newAllocationPeriodButton": "Nuevo período de asignación",
        "retirementPlanningAccordionButton": "Planificación de la Jubilación",
        "currentAgeLabel": "Edad actual",
        "retirementAgeLabel": "Edad de jubilación",
        "monthlyPensionLabel": "Pensión mensual (neta)",
        "withdrawalRateLabel": "Tasa de retiro (%)",
        "runSimulationButton": "Ejecutar Simulación",
        "resultsTitle": "Resultados",
        "helpModalTitle": "Ayuda",
        "helpModalWelcome": "¡Bienvenido al Planificador de Riqueza Interactivo!",
        "helpModalIntro": "Esta herramienta gratuita y de código abierto le ayuda a planificar y visualizar su futuro financiero.",
        "helpModalHowToUse": "Cómo utilizar:",
        "helpModalStep1": "<strong>Configuración:</strong> Ajuste la tasa de inflación como desee.",
        "helpModalStep2": "<strong>Datos financieros:</strong> Complete sus activos, pasivos, ingresos y gastos.",
        "helpModalStep3": "<strong>Asignación de ahorros:</strong> Determine cómo se invierten sus ahorros en diferentes períodos.",
        "helpModalStep4": "<strong>Planificación de la jubilación:</strong> Complete su edad actual, la edad de jubilación deseada y la pensión esperada.",
        "helpModalStep5": "<strong>Ejecutar simulación:</strong> Haga clic en el botón para ver la evolución de su riqueza.",
        "helpModalResultsInfo": "Los resultados se muestran en un gráfico y una tabla.",
        "helpModalButtonsInfo": "Con los botones en la parte superior derecha, puede importar, exportar o borrar todos sus datos.",
        "helpModalPrivacy": "La privacidad es lo primero: sus datos nunca se almacenarán ni compartirán de ninguna manera.",
        "helpModalSourceCode": "Código fuente disponible en: <a href=\"https://github.com/skapebolt/wealth-planner-tool\">https://github.com/skapebolt/wealth-planner-tool</a>",
        "nameLabel": "Nombre",
        "valueLabel": "Valor",
        "returnLabel": "Rendimiento (%)",
        "taxLabel": "Impuesto (%)",
        "startLabel": "Inicio",
        "endLabel": "Fin",
        "withdrawalOrderLabel": "Orden",
        "frequencyLabel": "Frecuencia",
        "indexedLabel": "Indexado",
        "monthlyOption": "Mensual",
        "yearlyOption": "Anual",
        "deleteAssetCategoryLabel": "Eliminar categoría de activo",
        "deleteLiabilityCategoryLabel": "Eliminar categoría de pasivo",
        "deleteIncomeCategoryLabel": "Eliminar categoría de ingresos",
        "deleteExpenseCategoryLabel": "Eliminar categoría de gastos",
        "deleteAllocationPeriodLabel": "Eliminar período de asignación",
        "startYearLabel": "Año de inicio",
        "clearDataConfirmation": "¿Está seguro de que desea borrar todos los datos?",
        "earlyRetirementMessage": "¡Es posible que pueda jubilarse anticipadamente en <strong>{year}</strong> a la edad de <strong>{age}</strong> con un patrimonio neto de <strong>{netWorth}</strong>!",
        "pensionWithdrawalMessage": "Su primer retiro anual al alcanzar la edad de jubilación sería de <strong>{amount}</strong> ({rate}% de {netWorth}), o <strong>{monthly}</strong> por mes.",
        "netWorthLabel": "Patrimonio neto",
        "yearHeader": "Año",
        "ageHeader": "Edad",
        "netIncomeHeader": "Ingresos netos",
        "expensesHeader": "Gastos",
        "savingsCapacityHeader": "Capacidad de ahorro",
        "savingsRateHeader": "Tasa de ahorro",
        "netWorthHeader": "Patrimonio neto",
        "assetHeader": "{asset} (Activo)",
        "liabilityHeader": "{liability} (Pasivo)",
        "ownHome": "Vivienda propia",
        "stocks": "Acciones",
        "savingsAccount": "Cuenta de ahorros",
        "mortgage": "Hipoteca",
        "salary": "Salario",
        "livingExpenses": "Gastos de manutención",
        "mortgageRepayment": "Pago de la hipoteca",
        "languageChangeWarning": "Al cambiar el idioma, se restablecerán todos sus datos. ¿Desea continuar?",
        "inflationTooltip": "El aumento anual promedio de los precios. Se utiliza para calcular el valor futuro del dinero.",
        "currentAgeTooltip": "Su edad actual en años.",
        "retirementAgeTooltip": "La edad a la que planea jubilarse.",
        "monthlyPensionTooltip": "La pensión mensual neta estimada que recibirá del gobierno.",
        "withdrawalRateTooltip": "El porcentaje de sus activos totales que planea retirar anualmente después de la jubilación (por ejemplo, la regla del 4%).",
        "assetNameTooltip": "Un nombre único para esta categoría.",
        "assetValueTooltip": "El valor actual en su moneda.",
        "assetReturnTooltip": "El rendimiento anual esperado de este activo, después de costos.",
        "assetTaxTooltip": "El impuesto anual sobre el rendimiento o la ganancia de capital.",
        "assetStartYearTooltip": "El año en que esta categoría se vuelve activa.",
        "assetEndYearTooltip": "El año en que esta categoría se detiene. Deje en blanco si no corresponde.",
        "assetWithdrawalOrderTooltip": "El orden de retiro en caso de déficit o después de la jubilación (1 = primero, 99 = último).",
        "liabilityNameTooltip": "Un nombre único para esta categoría.",
        "liabilityValueTooltip": "El valor actual en su moneda.",
        "liabilityStartYearTooltip": "El año en que esta categoría se vuelve activa.",
        "liabilityEndYearTooltip": "El año en que esta categoría se detiene. Deje en blanco si no corresponde.",
        "incomeNameTooltip": "Un nombre único para esta categoría.",
        "incomeValueTooltip": "El valor actual en su moneda.",
        "incomeFrequencyTooltip": "Con qué frecuencia se produce este ingreso.",
        "incomeIndexedTooltip": "Marque si esta cantidad debe aumentar anualmente con la inflación.",
        "incomeStartYearTooltip": "El año en que esta categoría se vuelve activa.",
        "incomeEndYearTooltip": "El año en que esta categoría se detiene. Deje en blanco si no corresponde.",
        "expenseNameTooltip": "Un nombre único para esta categoría.",
        "expenseValueTooltip": "El valor actual en su moneda.",
        "expenseFrequencyTooltip": "Con qué frecuencia se produce este gasto.",
        "expenseIndexedTooltip": "Marque si esta cantidad debe aumentar anualmente con la inflación.",
        "expenseStartYearTooltip": "El año en que esta categoría se vuelve activa.",
        "expenseEndYearTooltip": "El año en que esta categoría se detiene. Deje en blanco si no corresponde.",
        "languageAlreadySelected": "Este idioma ya está seleccionado.",
        "notificationTitle": "Notificación",
        "endYearBeforeStartYearError": "El año de fin no puede ser anterior al año de inicio.",
        "retirementAgeBeforeCurrentAgeError": "La edad de jubilación no puede ser menor que la edad actual.",
        "autoRebalanceLabel": "Rebalanceo automático",
        "autoRebalanceTooltip": "Si está marcada, los porcentajes de asignación de activos se mantendrán a lo largo de la simulación mediante el rebalanceo automático de la cartera."
    },
    "fr": {
        "pageTitle": "Planificateur de Patrimoine Interactif",
        "languageSelector": "Langue",
        "navbarBrand": "Planificateur de Patrimoine",
        "darkModeLabel": "Mode sombre",
        "importButton": "Importer",
        "exportButton": "Exporter",
        "clearButton": "Effacer",
        "settingsTitle": "Paramètres",
        "inflationLabel": "Inflation (%)",
        "financialDataTitle": "Données Financières",
        "assetsAccordionButton": "Actifs",
        "newAssetButton": "Nouvelle classe d'actifs",
        "liabilitiesAccordionButton": "Passifs",
        "newLiabilityButton": "Nouvelle classe de passifs",
        "incomeAccordionButton": "Revenus",
        "newIncomeButton": "Nouvelle catégorie de revenus",
        "expensesAccordionButton": "Dépenses",
        "newExpenseButton": "Nouvelle catégorie de dépenses",
        "savingsAllocationAccordionButton": "Allocation de l'Épargne",
        "newAllocationPeriodButton": "Nouvelle période d'allocation",
        "retirementPlanningAccordionButton": "Planification de la Retraite",
        "currentAgeLabel": "Âge actuel",
        "retirementAgeLabel": "Âge de la retraite",
        "monthlyPensionLabel": "Pension mensuelle (nette)",
        "withdrawalRateLabel": "Taux de retrait (%)",
        "runSimulationButton": "Lancer la simulation",
        "resultsTitle": "Résultats",
        "helpModalTitle": "Aide",
        "helpModalWelcome": "Bienvenue dans le Planificateur de Patrimoine Interactif !",
        "helpModalIntro": "Cet outil gratuit et open source vous aide à planifier et à visualiser votre avenir financier.",
        "helpModalHowToUse": "Comment utiliser :",
        "helpModalStep1": "<strong>Paramètres :</strong> Ajustez le taux d'inflation comme vous le souhaitez.",
        "helpModalStep2": "<strong>Données financières :</strong> Remplissez vos actifs, passifs, revenus et dépenses.",
        "helpModalStep3": "<strong>Allocation de l'épargne :</strong> Déterminez comment votre épargne est investie sur différentes périodes.",
        "helpModalStep4": "<strong>Planification de la retraite :</strong> Indiquez votre âge actuel, l'âge de la retraite souhaité et la pension prévue.",
        "helpModalStep5": "<strong>Lancer la simulation :</strong> Cliquez sur le bouton pour voir l'évolution de votre patrimoine.",
        "helpModalResultsInfo": "Les résultats sont affichés dans un graphique et un tableau.",
        "helpModalButtonsInfo": "Avec les boutons en haut à droite, vous pouvez importer, exporter ou effacer toutes vos données.",
        "helpModalPrivacy": "La confidentialité d'abord : Vos données ne seront jamais stockées ou partagées de quelque manière que ce soit.",
        "helpModalSourceCode": "Code source disponible sur : <a href=\"https://github.com/skapebolt/wealth-planner-tool\">https://github.com/skapebolt/wealth-planner-tool</a>",
        "nameLabel": "Nom",
        "valueLabel": "Valeur",
        "returnLabel": "Rendement (%)",
        "taxLabel": "Impôt (%)",
        "startLabel": "Début",
        "endLabel": "Fin",
        "withdrawalOrderLabel": "Ordre",
        "frequencyLabel": "Fréquence",
        "indexedLabel": "Indexé",
        "monthlyOption": "Mensuel",
        "yearlyOption": "Annuel",
        "deleteAssetCategoryLabel": "Supprimer la catégorie d'actifs",
        "deleteLiabilityCategoryLabel": "Supprimer la catégorie de passifs",
        "deleteIncomeCategoryLabel": "Supprimer la catégorie de revenus",
        "deleteExpenseCategoryLabel": "Supprimer la catégorie de dépenses",
        "deleteAllocationPeriodLabel": "Supprimer la période d'allocation",
        "startYearLabel": "Année de début",
        "clearDataConfirmation": "Êtes-vous sûr de vouloir effacer toutes les données ?",
        "earlyRetirementMessage": "Vous pourriez être en mesure de prendre une retraite anticipée en <strong>{year}</strong> à l'âge de <strong>{age}</strong> avec une valeur nette de <strong>{netWorth}</strong> !",
        "pensionWithdrawalMessage": "Votre premier retrait annuel à l'âge de la retraite serait de <strong>{amount}</strong> ({rate}% de {netWorth}), ou <strong>{monthly}</strong> par mois.",
        "netWorthLabel": "Valeur nette",
        "yearHeader": "Année",
        "ageHeader": "Âge",
        "netIncomeHeader": "Revenu net",
        "expensesHeader": "Dépenses",
        "savingsCapacityHeader": "Capacité d'épargne",
        "savingsRateHeader": "Taux d'épargne",
        "netWorthHeader": "Valeur nette",
        "assetHeader": "{asset} (Actif)",
        "liabilityHeader": "{liability} (Passif)",
        "ownHome": "Propre maison",
        "stocks": "Actions",
        "savingsAccount": "Compte d'épargne",
        "mortgage": "Hypothèque",
        "salary": "Salaire",
        "livingExpenses": "Frais de subsistance",
        "mortgageRepayment": "Remboursement de l'hypothèque",
        "languageChangeWarning": "Changer la langue réinitialisera toutes vos données. Voulez-vous continuer ?",
        "inflationTooltip": "L'augmentation annuelle moyenne des prix. Ceci est utilisé pour calculer la valeur future de l'argent.",
        "currentAgeTooltip": "Votre âge actuel en années.",
        "retirementAgeTooltip": "L'âge auquel vous prévoyez de prendre votre retraite.",
        "monthlyPensionTooltip": "La pension mensuelle nette estimée que vous recevrez du gouvernement.",
        "withdrawalRateTooltip": "Le pourcentage de votre patrimoine total que vous prévoyez de retirer annuellement après la retraite (par exemple, la règle des 4%).",
        "assetNameTooltip": "Un nom unique pour cette catégorie.",
        "assetValueTooltip": "La valeur actuelle dans votre devise.",
        "assetReturnTooltip": "Le rendement annuel attendu de cet actif, après coûts.",
        "assetTaxTooltip": "L'impôt annuel sur le rendement ou la plus-value.",
        "assetStartYearTooltip": "L'année où cette catégorie devient active.",
        "assetEndYearTooltip": "L'année où cette catégorie s'arrête. Laissez vide si non applicable.",
        "assetWithdrawalOrderTooltip": "L'ordre de retrait en cas de déficit ou après la retraite (1 = premier, 99 = dernier).",
        "liabilityNameTooltip": "Un nom unique pour cette catégorie.",
        "liabilityValueTooltip": "La valeur actuelle dans votre devise.",
        "liabilityStartYearTooltip": "L'année où cette catégorie devient active.",
        "liabilityEndYearTooltip": "L'année où cette catégorie s'arrête. Laissez vide si non applicable.",
        "incomeNameTooltip": "Un nom unique pour cette catégorie.",
        "incomeValueTooltip": "La valeur actuelle dans votre devise.",
        "incomeFrequencyTooltip": "La fréquence à laquelle ce revenu se produit.",
        "incomeIndexedTooltip": "Cochez si ce montant doit augmenter annuellement avec l'inflation.",
        "incomeStartYearTooltip": "L'année où cette catégorie devient active.",
        "incomeEndYearTooltip": "L'année où cette catégorie s'arrête. Laissez vide si non applicable.",
        "expenseNameTooltip": "Un nom unique pour cette catégorie.",
        "expenseValueTooltip": "La valeur actuelle dans votre devise.",
        "expenseFrequencyTooltip": "La fréquence à laquelle cette dépense se produit.",
        "expenseIndexedTooltip": "Cochez si ce montant doit augmenter annuellement avec l'inflation.",
        "expenseStartYearTooltip": "L'année où cette catégorie devient active.",
        "expenseEndYearTooltip": "L'année où cette catégorie s'arrête. Laissez vide si non applicable.",
        "languageAlreadySelected": "Cette langue est déjà sélectionnée.",
        "notificationTitle": "Notification",
        "endYearBeforeStartYearError": "L'année de fin ne peut pas être antérieure à l'année de début.",
        "retirementAgeBeforeCurrentAgeError": "L'âge de la retraite ne peut pas être inférieur à l'âge actuel.",
        "autoRebalanceLabel": "Rééquilibrage automatique",
        "autoRebalanceTooltip": "Si cette case est cochée, les pourcentages d'allocation d'actifs seront maintenus tout au long de la simulation en rééquilibrant automatiquement le portefeuille."
    },
    "it": {
        "pageTitle": "Pianificatore Patrimoniale Interattivo",
        "languageSelector": "Lingua",
        "navbarBrand": "Pianificatore Patrimoniale",
        "darkModeLabel": "Modalità oscura",
        "importButton": "Importa",
        "exportButton": "Esporta",
        "clearButton": "Cancella",
        "settingsTitle": "Impostazioni",
        "inflationLabel": "Inflazione (%)",
        "financialDataTitle": "Dati Finanziari",
        "assetsAccordionButton": "Attività",
        "newAssetButton": "Nuova classe di attività",
        "liabilitiesAccordionButton": "Passività",
        "newLiabilityButton": "Nuova classe di passività",
        "incomeAccordionButton": "Reddito",
        "newIncomeButton": "Nuova categoria di reddito",
        "expensesAccordionButton": "Spese",
        "newExpenseButton": "Nuova categoria di spesa",
        "savingsAllocationAccordionButton": "Allocazione dei Risparmi",
        "newAllocationPeriodButton": "Nuovo periodo di allocazione",
        "retirementPlanningAccordionButton": "Pianificazione della Pensione",
        "currentAgeLabel": "Età attuale",
        "retirementAgeLabel": "Età pensionabile",
        "monthlyPensionLabel": "Pensione mensile (netta)",
        "withdrawalRateLabel": "Tasso di prelievo (%)",
        "runSimulationButton": "Esegui Simulazione",
        "resultsTitle": "Risultati",
        "helpModalTitle": "Aiuto",
        "helpModalWelcome": "Benvenuti nel Pianificatore Patrimoniale Interattivo!",
        "helpModalIntro": "Questo strumento gratuito e open source ti aiuta a pianificare e visualizzare il tuo futuro finanziario.",
        "helpModalHowToUse": "Come usare:",
        "helpModalStep1": "<strong>Impostazioni:</strong> Regola il tasso di inflazione come desiderato.",
        "helpModalStep2": "<strong>Dati finanziari:</strong> Inserisci le tue attività, passività, entrate e uscite.",
        "helpModalStep3": "<strong>Allocazione dei risparmi:</strong> Determina come vengono investiti i tuoi risparmi in diversi periodi.",
        "helpModalStep4": "<strong>Pianificazione della pensione:</strong> Inserisci la tua età attuale, l'età pensionabile desiderata e la pensione prevista.",
        "helpModalStep5": "<strong>Esegui simulazione:</strong> Fai clic sul pulsante per vedere l'evoluzione del tuo patrimonio.",
        "helpModalResultsInfo": "I risultati vengono visualizzati in un grafico e in una tabella.",
        "helpModalButtonsInfo": "Con i pulsanti in alto a destra, puoi importare, esportare o cancellare tutti i tuoi dati.",
        "helpModalPrivacy": "La privacy prima di tutto: i tuoi dati non verranno mai archiviati o condivisi in alcun modo.",
        "helpModalSourceCode": "Codice sorgente disponibile su: <a href=\"https://github.com/skapebolt/wealth-planner-tool\">https://github.com/skapebolt/wealth-planner-tool</a>",
        "nameLabel": "Nome",
        "valueLabel": "Valore",
        "returnLabel": "Rendimento (%)",
        "taxLabel": "Tassa (%)",
        "startLabel": "Inizio",
        "endLabel": "Fine",
        "withdrawalOrderLabel": "Ordine",
        "frequencyLabel": "Frequenza",
        "indexedLabel": "Indicizzato",
        "monthlyOption": "Mensile",
        "yearlyOption": "Annuale",
        "deleteAssetCategoryLabel": "Elimina categoria di attività",
        "deleteLiabilityCategoryLabel": "Elimina categoria di passività",
        "deleteIncomeCategoryLabel": "Elimina categoria di reddito",
        "deleteExpenseCategoryLabel": "Elimina categoria di spesa",
        "deleteAllocationPeriodLabel": "Elimina periodo di allocazione",
        "startYearLabel": "Anno di inizio",
        "clearDataConfirmation": "Sei sicuro di voler cancellare tutti i dati?",
        "earlyRetirementMessage": "Potresti essere in grado di andare in pensione anticipata nel <strong>{year}</strong> all'età di <strong>{age}</strong> con un patrimonio netto di <strong>{netWorth}</strong>!",
        "pensionWithdrawalMessage": "Il tuo primo prelievo annuale al raggiungimento dell'età pensionabile sarebbe di <strong>{amount}</strong> ({rate}% di {netWorth}), o <strong>{monthly}</strong> al mese.",
        "netWorthLabel": "Patrimonio netto",
        "yearHeader": "Anno",
        "ageHeader": "Età",
        "netIncomeHeader": "Reddito netto",
        "expensesHeader": "Spese",
        "savingsCapacityHeader": "Capacità di risparmio",
        "savingsRateHeader": "Tasso di risparmio",
        "netWorthHeader": "Patrimonio netto",
        "assetHeader": "{asset} (Attività)",
        "liabilityHeader": "{liability} (Passività)",
        "ownHome": "Casa di proprietà",
        "stocks": "Azioni",
        "savingsAccount": "Conto di risparmio",
        "mortgage": "Mutuo",
        "salary": "Stipendio",
        "livingExpenses": "Spese di sostentamento",
        "mortgageRepayment": "Rimborso del mutuo",
        "languageChangeWarning": "Il cambio di lingua azzererà tutti i tuoi dati. Vuoi procedere?",
        "inflationTooltip": "L'aumento medio annuo dei prezzi. Viene utilizzato per calcolare il valore futuro del denaro.",
        "currentAgeTooltip": "La tua età attuale in anni.",
        "retirementAgeTooltip": "L'età in cui prevedi di andare in pensione.",
        "monthlyPensionTooltip": "La pensione mensile netta stimata che riceverai dal governo.",
        "withdrawalRateTooltip": "La percentuale del tuo patrimonio totale che prevedi di prelevare annualmente dopo la pensione (ad es. la regola del 4%).",
        "assetNameTooltip": "Un nome univoco per questa categoria.",
        "assetValueTooltip": "Il valore corrente nella tua valuta.",
        "assetReturnTooltip": "Il rendimento annuo previsto di questa attività, al netto dei costi.",
        "assetTaxTooltip": "L'imposta annuale sul rendimento o sulla plusvalenza.",
        "assetStartYearTooltip": "L'anno in cui questa categoria diventa attiva.",
        "assetEndYearTooltip": "L'anno in cui questa categoria si ferma. Lasciare vuoto se non applicabile.",
        "assetWithdrawalOrderTooltip": "L'ordine di prelievo in caso di disavanzo o dopo il pensionamento (1 = primo, 99 = ultimo).",
        "liabilityNameTooltip": "Un nome univoco per questa categoria.",
        "liabilityValueTooltip": "Il valore corrente nella tua valuta.",
        "liabilityStartYearTooltip": "L'anno in cui questa categoria diventa attiva.",
        "liabilityEndYearTooltip": "L'anno in cui questa categoria si ferma. Lasciare vuoto se non applicabile.",
        "incomeNameTooltip": "Un nome univoco per questa categoria.",
        "incomeValueTooltip": "Il valore corrente nella tua valuta.",
        "incomeFrequencyTooltip": "Con quale frequenza si verifica questo reddito.",
        "incomeIndexedTooltip": "Controlla se questo importo dovrebbe aumentare annualmente con l'inflazione.",
        "incomeStartYearTooltip": "L'anno in cui questa categoria diventa attiva.",
        "incomeEndYearTooltip": "L'anno in cui questa categoria si ferma. Lasciare vuoto se non applicabile.",
        "expenseNameTooltip": "Un nome univoco per questa categoria.",
        "expenseValueTooltip": "Il valore corrente nella tua valuta.",
        "expenseFrequencyTooltip": "Con quale frequenza si verifica questa spesa.",
        "expenseIndexedTooltip": "Controlla se questo importo dovrebbe aumentare annualmente con l'inflazione.",
        "expenseStartYearTooltip": "L'anno in cui questa categoria diventa attiva.",
        "expenseEndYearTooltip": "L'anno in cui questa categoria si ferma. Lasciare vuoto se non applicabile.",
        "languageAlreadySelected": "Questa lingua è già selezionata.",
        "notificationTitle": "Notifica",
        "endYearBeforeStartYearError": "L'anno di fine non può essere precedente all'anno di inizio.",
        "retirementAgeBeforeCurrentAgeError": "L'età pensionabile non può essere inferiore all'età attuale.",
        "autoRebalanceLabel": "Ribilanciamento automatico",
        "autoRebalanceTooltip": "Se selezionato, le percentuali di allocazione degli asset verranno mantenute durante la simulazione ribilanciando automaticamente il portafoglio."
    },
    "nl": {
        "pageTitle": "Interactieve Vermogensplanner",
        "languageSelector": "Taal",
        "navbarBrand": "Vermogensplanner",
        "darkModeLabel": "Donkere modus",
        "importButton": "Importeren",
        "exportButton": "Exporteren",
        "clearButton": "Wissen",
        "settingsTitle": "Instellingen",
        "inflationLabel": "Inflatie (%)",
        "financialDataTitle": "Financiële Gegevens",
        "assetsAccordionButton": "Activa",
        "newAssetButton": "Nieuwe activaklasse",
        "liabilitiesAccordionButton": "Passiva",
        "newLiabilityButton": "Nieuwe passivaklasse",
        "incomeAccordionButton": "Inkomen",
        "newIncomeButton": "Nieuwe inkomenscategorie",
        "expensesAccordionButton": "Uitgaven",
        "newExpenseButton": "Nieuwe uitgavencategorie",
        "savingsAllocationAccordionButton": "Spaarallocatie",
        "newAllocationPeriodButton": "Nieuwe allocatieperiode",
        "retirementPlanningAccordionButton": "Pensioenplanning",
        "currentAgeLabel": "Huidige leeftijd",
        "retirementAgeLabel": "Pensioenleeftijd",
        "monthlyPensionLabel": "Maandelijks pensioen (netto)",
        "withdrawalRateLabel": "Opnamepercentage (%)",
        "runSimulationButton": "Simulatie uitvoeren",
        "resultsTitle": "Resultaten",
        "helpModalTitle": "Hulp",
        "helpModalWelcome": "Welkom bij de Interactieve Vermogensplanner!",
        "helpModalIntro": "Deze gratis en open source tool helpt u uw financiële toekomst te plannen en te visualiseren.",
        "helpModalHowToUse": "Hoe te gebruiken:",
        "helpModalStep1": "<strong>Instellingen:</strong> Pas het inflatiepercentage naar wens aan.",
        "helpModalStep2": "<strong>Financiële gegevens:</strong> Vul uw bezittingen, schulden, inkomsten en uitgaven in.",
        "helpModalStep3": "<strong>Spaarallocatie:</strong> Bepaal hoe uw spaargeld over verschillende perioden wordt belegd.",
        "helpModalStep4": "<strong>Pensioenplanning:</strong> Vul uw huidige leeftijd, gewenste pensioenleeftijd en verwacht pensioen in.",
        "helpModalStep5": "<strong>Simulatie uitvoeren:</strong> Klik op de knop om de evolutie van uw vermogen te zien.",
        "helpModalResultsInfo": "De resultaten worden weergegeven in een grafiek en een tabel.",
        "helpModalButtonsInfo": "Met de knoppen rechtsboven kunt u al uw gegevens importeren, exporteren of wissen.",
        "helpModalPrivacy": "Privacy voorop: uw gegevens worden nooit opgeslagen of gedeeld, in welke vorm dan ook.",
        "helpModalSourceCode": "Broncode beschikbaar op: <a href=\"https://github.com/skapebolt/wealth-planner-tool\">https://github.com/skapebolt/wealth-planner-tool</a>",
        "nameLabel": "Naam",
        "valueLabel": "Waarde",
        "returnLabel": "Rendement (%)",
        "taxLabel": "Belasting (%)",
        "startLabel": "Start",
        "endLabel": "Einde",
        "withdrawalOrderLabel": "Volgorde",
        "frequencyLabel": "Frequentie",
        "indexedLabel": "Geïndexeerd",
        "monthlyOption": "Maandelijks",
        "yearlyOption": "Jaarlijks",
        "deleteAssetCategoryLabel": "Activaklasse verwijderen",
        "deleteLiabilityCategoryLabel": "Passiviteitsklasse verwijderen",
        "deleteIncomeCategoryLabel": "Inkomenscategorie verwijderen",
        "deleteExpenseCategoryLabel": "Uitgavencategorie verwijderen",
        "deleteAllocationPeriodLabel": "Allocatieperiode verwijderen",
        "startYearLabel": "Startjaar",
        "clearDataConfirmation": "Weet u zeker dat u alle gegevens wilt wissen?",
        "earlyRetirementMessage": "U kunt mogelijk vervroegd met pensioen in <strong>{year}</strong> op <strong>{age}</strong>-jarige leeftijd met een netto vermogen van <strong>{netWorth}</strong>!",
        "pensionWithdrawalMessage": "Uw eerste jaarlijkse opname bij het bereiken van de pensioenleeftijd zou <strong>{amount}</strong> ({rate}% van {netWorth}) zijn, of <strong>{monthly}</strong> per maand.",
        "netWorthLabel": "Netto vermogen",
        "yearHeader": "Jaar",
        "ageHeader": "Leeftijd",
        "netIncomeHeader": "Netto inkomen",
        "expensesHeader": "Uitgaven",
        "savingsCapacityHeader": "Spaarcapaciteit",
        "savingsRateHeader": "Spaargraad",
        "netWorthHeader": "Netto vermogen",
        "assetHeader": "{asset} (Activa)",
        "liabilityHeader": "{liability} (Passiva)",
        "ownHome": "Eigen Woning",
        "stocks": "Aandelen",
        "savingsAccount": "Spaarrekening",
        "mortgage": "Hypotheek",
        "salary": "Salaris",
        "livingExpenses": "Levenskosten",
        "mortgageRepayment": "Aflossing hypotheek",
        "languageChangeWarning": "Het wijzigen van de taal zal al uw gegevens resetten. Wilt u doorgaan?",
        "inflationTooltip": "De gemiddelde jaarlijkse prijsstijging. Dit wordt gebruikt om de toekomstige waarde van geld te berekenen.",
        "currentAgeTooltip": "Uw huidige leeftijd in jaren.",
        "retirementAgeTooltip": "De leeftijd waarop u van plan bent met pensioen te gaan.",
        "monthlyPensionTooltip": "Het geschatte netto maandelijkse pensioen dat u van de overheid zult ontvangen.",
        "withdrawalRateTooltip": "Het percentage van uw totale vermogen dat u jaarlijks na uw pensionering van plan bent op te nemen (bijv. de 4%-regel).",
        "assetNameTooltip": "Een unieke naam voor deze categorie.",
        "assetValueTooltip": "De huidige waarde in uw valuta.",
        "assetReturnTooltip": "Het verwachte jaarlijkse rendement op dit activum, na kosten.",
        "assetTaxTooltip": "De jaarlijkse belasting op het rendement of de vermogenswinst.",
        "assetStartYearTooltip": "Het jaar waarin deze categorie actief wordt.",
        "assetEndYearTooltip": "Het jaar waarin deze categorie stopt. Laat leeg indien niet van toepassing.",
        "assetWithdrawalOrderTooltip": "De opnamevolgorde in geval van een tekort of na pensionering (1 = eerst, 99 = laatst).",
        "liabilityNameTooltip": "Een unieke naam voor deze categorie.",
        "liabilityValueTooltip": "De huidige waarde in uw valuta.",
        "liabilityStartYearTooltip": "Het jaar waarin deze categorie actief wordt.",
        "liabilityEndYearTooltip": "Het jaar waarin deze categorie stopt. Laat leeg indien niet van toepassing.",
        "incomeNameTooltip": "Een unieke naam voor deze categorie.",
        "incomeValueTooltip": "De huidige waarde in uw valuta.",
        "incomeFrequencyTooltip": "Hoe vaak dit inkomen voorkomt.",
        "incomeIndexedTooltip": "Vink aan als dit bedrag jaarlijks met de inflatie moet stijgen.",
        "incomeStartYearTooltip": "Het jaar waarin deze categorie actief wordt.",
        "incomeEndYearTooltip": "Het jaar waarin deze categorie stopt. Laat leeg indien niet van toepassing.",
        "expenseNameTooltip": "Een unieke naam voor deze categorie.",
        "expenseValueTooltip": "De huidige waarde in uw valuta.",
        "expenseFrequencyTooltip": "Hoe vaak deze uitgave voorkomt.",
        "expenseIndexedTooltip": "Vink aan als dit bedrag jaarlijks met de inflatie moet stijgen.",
        "expenseStartYearTooltip": "Het jaar waarin deze categorie actief wordt.",
        "expenseEndYearTooltip": "Het jaar waarin deze categorie stopt. Laat leeg indien niet van toepassing.",
        "languageAlreadySelected": "Deze taal is al geselecteerd.",
        "notificationTitle": "Melding",
        "endYearBeforeStartYearError": "Eindjaar kan niet vóór startjaar liggen.",
        "retirementAgeBeforeCurrentAgeError": "Pensioenleeftijd kan niet lager zijn dan huidige leeftijd.",
        "autoRebalanceLabel": "Automatisch herbalanceren",
        "autoRebalanceTooltip": "Indien aangevinkt, blijven de percentages van de activaspreiding gedurende de simulatie behouden door de portefeuille automatisch te herbalanceren."
    },
    "pt": {
        "pageTitle": "Planejador de Riqueza Interativo",
        "languageSelector": "Idioma",
        "navbarBrand": "Planejador de Riqueza",
        "darkModeLabel": "Modo escuro",
        "importButton": "Importar",
        "exportButton": "Exportar",
        "clearButton": "Limpar",
        "settingsTitle": "Configurações",
        "inflationLabel": "Inflação (%)",
        "financialDataTitle": "Dados Financeiros",
        "assetsAccordionButton": "Ativos",
        "newAssetButton": "Nova classe de ativos",
        "liabilitiesAccordionButton": "Passivos",
        "newLiabilityButton": "Nova classe de passivos",
        "incomeAccordionButton": "Renda",
        "newIncomeButton": "Nova categoria de renda",
        "expensesAccordionButton": "Despesas",
        "newExpenseButton": "Nova categoria de despesa",
        "savingsAllocationAccordionButton": "Alocação de Poupança",
        "newAllocationPeriodButton": "Novo período de alocação",
        "retirementPlanningAccordionButton": "Planejamento de Aposentadoria",
        "currentAgeLabel": "Idade atual",
        "retirementAgeLabel": "Idade de aposentadoria",
        "monthlyPensionLabel": "Pensão mensal (líquida)",
        "withdrawalRateLabel": "Taxa de retirada (%)",
        "runSimulationButton": "Executar Simulação",
        "resultsTitle": "Resultados",
        "helpModalTitle": "Ajuda",
        "helpModalWelcome": "Bem-vindo ao Planejador de Riqueza Interativo!",
        "helpModalIntro": "Esta ferramenta gratuita e de código aberto ajuda você a planejar e visualizar seu futuro financeiro.",
        "helpModalHowToUse": "Como usar:",
        "helpModalStep1": "<strong>Configurações:</strong> Ajuste a taxa de inflação conforme desejado.",
        "helpModalStep2": "<strong>Dados financeiros:</strong> Preencha seus ativos, passivos, receitas e despesas.",
        "helpModalStep3": "<strong>Alocação de poupança:</strong> Determine como suas economias são investidas em diferentes períodos.",
        "helpModalStep4": "<strong>Planejamento de aposentadoria:</strong> Preencha sua idade atual, idade de aposentadoria desejada e pensão esperada.",
        "helpModalStep5": "<strong>Executar simulação:</strong> Clique no botão para ver a evolução de sua riqueza.",
        "helpModalResultsInfo": "Os resultados são exibidos em um gráfico e uma tabela.",
        "helpModalButtonsInfo": "Com os botões no canto superior direito, você pode importar, exportar ou limpar todos os seus dados.",
        "helpModalPrivacy": "Privacidade em primeiro lugar: seus dados nunca serão armazenados ou compartilhados de forma alguma.",
        "helpModalSourceCode": "Código-fonte disponível em: <a href=\"https://github.com/skapebolt/wealth-planner-tool\">https://github.com/skapebolt/wealth-planner-tool</a>",
        "nameLabel": "Nome",
        "valueLabel": "Valor",
        "returnLabel": "Retorno (%)",
        "taxLabel": "Imposto (%)",
        "startLabel": "Início",
        "endLabel": "Fim",
        "withdrawalOrderLabel": "Ordem",
        "frequencyLabel": "Frequência",
        "indexedLabel": "Indexado",
        "monthlyOption": "Mensal",
        "yearlyOption": "Anual",
        "deleteAssetCategoryLabel": "Excluir categoria de ativo",
        "deleteLiabilityCategoryLabel": "Excluir categoria de passivo",
        "deleteIncomeCategoryLabel": "Excluir categoria de renda",
        "deleteExpenseCategoryLabel": "Excluir categoria de despesa",
        "deleteAllocationPeriodLabel": "Excluir período de alocação",
        "startYearLabel": "Ano de início",
        "clearDataConfirmation": "Tem certeza de que deseja limpar todos os dados?",
        "earlyRetirementMessage": "Você pode conseguir se aposentar mais cedo em <strong>{year}</strong> aos <strong>{age}</strong> anos com um patrimônio líquido de <strong>{netWorth}</strong>!",
        "pensionWithdrawalMessage": "Sua primeira retirada anual ao atingir a idade de aposentadoria seria de <strong>{amount}</strong> ({rate}% de {netWorth}), ou <strong>{monthly}</strong> por mês.",
        "netWorthLabel": "Patrimônio líquido",
        "yearHeader": "Ano",
        "ageHeader": "Idade",
        "netIncomeHeader": "Renda líquida",
        "expensesHeader": "Despesas",
        "savingsCapacityHeader": "Capacidade de poupança",
        "savingsRateHeader": "Taxa de poupança",
        "netWorthHeader": "Patrimônio líquido",
        "assetHeader": "{asset} (Ativo)",
        "liabilityHeader": "{liability} (Passivo)",
        "ownHome": "Casa própria",
        "stocks": "Ações",
        "savingsAccount": "Conta poupança",
        "mortgage": "Hipoteca",
        "salary": "Salário",
        "livingExpenses": "Despesas de subsistência",
        "mortgageRepayment": "Pagamento da hipoteca",
        "languageChangeWarning": "A alteração do idioma redefinirá todos os seus dados. Deseja continuar?",
        "inflationTooltip": "O aumento médio anual dos preços. É usado para calcular o valor futuro do dinheiro.",
        "currentAgeTooltip": "Sua idade atual em anos.",
        "retirementAgeTooltip": "A idade em que você planeja se aposentar.",
        "monthlyPensionTooltip": "A pensão mensal líquida estimada que você receberá do governo.",
        "withdrawalRateTooltip": "A porcentagem de seus ativos totais que você planeja retirar anualmente após a aposentadoria (por exemplo, a regra dos 4%).",
        "assetNameTooltip": "Um nome exclusivo para esta categoria.",
        "assetValueTooltip": "O valor atual em sua moeda.",
        "assetReturnTooltip": "O retorno anual esperado deste ativo, após os custos.",
        "assetTaxTooltip": "O imposto anual sobre o retorno ou ganho de capital.",
        "assetStartYearTooltip": "O ano em que esta categoria se torna ativa.",
        "assetEndYearTooltip": "O ano em que esta categoria para. Deixe em branco se não for aplicável.",
        "assetWithdrawalOrderTooltip": "A ordem de retirada em caso de déficit ou após a aposentadoria (1 = primeiro, 99 = último).",
        "liabilityNameTooltip": "Um nome exclusivo para esta categoria.",
        "liabilityValueTooltip": "O valor atual em sua moeda.",
        "liabilityStartYearTooltip": "O ano em que esta categoria se torna ativa.",
        "liabilityEndYearTooltip": "O ano em que esta categoria para. Deixe em branco se não for aplicável.",
        "incomeNameTooltip": "Um nome exclusivo para esta categoria.",
        "incomeValueTooltip": "O valor atual em sua moeda.",
        "incomeFrequencyTooltip": "Com que frequência essa renda ocorre.",
        "incomeIndexedTooltip": "Verifique se este valor deve aumentar anualmente com a inflação.",
        "incomeStartYearTooltip": "O ano em que esta categoria se torna ativa.",
        "incomeEndYearTooltip": "O ano em que esta categoria para. Deixe em branco se não for aplicável.",
        "expenseNameTooltip": "Um nome exclusivo para esta categoria.",
        "expenseValueTooltip": "O valor atual em sua moeda.",
        "expenseFrequencyTooltip": "Com que frequência essa despesa ocorre.",
        "expenseIndexedTooltip": "Verifique se este valor deve aumentar anualmente com a inflação.",
        "expenseStartYearTooltip": "O ano em que esta categoria se torna ativa.",
        "expenseEndYearTooltip": "O ano em que esta categoria para. Deixe em branco se não for aplicável.",
        "languageAlreadySelected": "Este idioma já está selecionado.",
        "notificationTitle": "Notificação",
        "endYearBeforeStartYearError": "O ano final não pode ser anterior ao ano inicial.",
        "retirementAgeBeforeCurrentAgeError": "A idade de aposentadoria não pode ser menor que a idade atual.",
        "autoRebalanceLabel": "Rebalanceamento automático",
        "autoRebalanceTooltip": "Se marcada, as percentagens de alocação de ativos serão mantidas ao longo da simulação através do rebalanceamento automático da carteira."
    }
};

let currentLang = 'en';

async function setLanguage(lang) {
    currentLang = lang;
    document.documentElement.lang = lang;

    // Use embedded translations instead of fetching
    if (!ALL_TRANSLATIONS[lang]) {
        console.error(`Translations for language '${lang}' not found in embedded data.`);
        // Fallback to English if the language data is not found
        if (lang !== 'en' && ALL_TRANSLATIONS['en']) {
            currentLang = 'en';
            document.documentElement.lang = 'en';
        } else {
            return; // No fallback possible
        }
    }

    translatePage();
    // Dispatch a custom event to notify other scripts that the language has changed
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang: currentLang } }));
}

function translatePage() {
    const langTranslations = ALL_TRANSLATIONS[currentLang];
    if (!langTranslations) {
        return;
    }

    document.querySelectorAll('[data-i18n-key]').forEach(element => {
        const key = element.getAttribute('data-i18n-key');
        if (langTranslations[key]) {
            const icon = element.querySelector('i');
            // Replace only the text content, preserving the icon
            element.innerHTML = langTranslations[key];
            if (icon) {
                element.appendChild(document.createTextNode(' '));
                element.appendChild(icon);
            }
        }
    });

    document.querySelectorAll('[data-i18n-title-key]').forEach(element => {
        const key = element.getAttribute('data-i18n-title-key');
        if (langTranslations[key]) {
            element.setAttribute('title', langTranslations[key]);
        }
    });

    if (langTranslations['pageTitle']) {
        document.title = langTranslations['pageTitle'];
    }
}

function getTranslation(key, replacements = {}) {
    const langTranslations = ALL_TRANSLATIONS[currentLang];
    let translation = langTranslations && langTranslations[key] ? langTranslations[key] : key;

    for (const placeholder in replacements) {
        translation = translation.replace(`{${placeholder}}`, replacements[placeholder]);
    }

    return translation;
}

document.addEventListener('DOMContentLoaded', () => {
    const userLang = (navigator.language || navigator.userLanguage).split('-')[0];
    const supportedLangs = [
        { code: 'en', name: 'English' },
        { code: 'fr', name: 'Français' },
        { code: 'es', name: 'Español' },
        { code: 'de', name: 'Deutsch' },
        { code: 'it', name: 'Italiano' },
        { code: 'pt', name: 'Português' },
        { code: 'nl', name: 'Nederlands' },
    ];
    
    let langToSet = 'en';
    if (supportedLangs.some(l => l.code === userLang)) {
        langToSet = userLang;
    }
    
        // Add the language selector to the navbar
    const darkModeToggleContainer = document.querySelector('.form-check.form-switch');
    if (darkModeToggleContainer) {
        const dropdownDiv = document.createElement('div');
        dropdownDiv.className = 'dropdown ms-2 me-2';

        const dropdownButton = document.createElement('button');
        dropdownButton.className = 'btn btn-secondary dropdown-toggle';
        dropdownButton.type = 'button';
        dropdownButton.id = 'language-selector';
        dropdownButton.setAttribute('data-bs-toggle', 'dropdown');
        dropdownButton.setAttribute('aria-expanded', 'false');
        dropdownButton.textContent = 'Language';

        const dropdownMenu = document.createElement('ul');
        dropdownMenu.className = 'dropdown-menu';
        dropdownMenu.setAttribute('aria-labelledby', 'language-selector');

        supportedLangs.forEach(lang => {
            const li = document.createElement('li');
            const a = document.createElement('a');
            a.className = 'dropdown-item';
            a.href = '#';
            a.textContent = lang.name;
            a.onclick = (e) => {
                e.preventDefault();
                if (lang.code === currentLang) {
                    alert(getTranslation('languageAlreadySelected'));
                    return;
                }
                if (confirm(getTranslation('languageChangeWarning'))) {
                    setLanguage(lang.code);
                }
            };
            li.appendChild(a);
            dropdownMenu.appendChild(li);
        });

        dropdownDiv.appendChild(dropdownButton);
        dropdownDiv.appendChild(dropdownMenu);
        darkModeToggleContainer.insertAdjacentElement('afterend', dropdownDiv);
    }

    setLanguage(langToSet);
});

window.addEventListener('languageChanged', (e) => {
    const lang = e.detail.lang;
    const langTranslations = ALL_TRANSLATIONS[lang];
    if (!langTranslations) return;

    const languageSelector = document.getElementById('language-selector');
    if (languageSelector) {
        languageSelector.textContent = langTranslations['languageSelector'] || 'Language';
    }
});
