const ALL_TRANSLATIONS = {
    "de": {
        "pageTitle": "SquirrelPlan",
        "languageSelector": "Sprache",
        "navbarBrand": "SquirrelPlan",
        "darkModeLabel": "Dunkelmodus",
        "importButton": "Importieren",
        "exportButton": "Exportieren",
        "clearButton": "Löschen",
        "settingsTitle": "Einstellungen",
        "inflationLabel": "Inflation (%)",
        "financialDataTitle": "Finanzdaten",
        "assetsAccordionButton": "Vermögenswerte",
        "newAssetButton": "Neue Anlageklasse",
        "liabilitiesAccordionButton": "Verbindlichkeiten",
        "newLiabilityButton": "Neue Haftungsklasse",
        "incomeAccordionButton": "Einkommen",
        "newIncomeButton": "Neue Einkommenskategorie",
        "expensesAccordionButton": "Ausgaben",
        "newExpenseButton": "Neue Ausgabenkategorie",
        "savingsAllocationAccordionButton": "Sparzuweisung",
        "newAllocationPeriodButton": "Neuer Zuweisungszeitraum",
        "retirementPlanningAccordionButton": "Ruhestands Planung",
        "currentAgeLabel": "Aktuelles Alter",
        "legalRetirementAgeLabel": "Gesetzliches Rentenalter",
        "monthlyPensionLabel": "Monatliche Rente (netto)",
        "withdrawalRateLabel": "Entnahmerate (%)",
        "runStandardSimulationButton": "Standard-Simulation durchführen",
        "runMonteCarloSimulationButton": "Monte-Carlo-Simulation durchführen",
        "resultsTitle": "Ergebnisse",
        "helpModalTitle": "Hilfe",
        "advancedAccordionButton": "Fortgeschritten",
        "earlyRetirementAgeLabel": "Frührentenalter",
        "enableMonteCarloLabel": "Monte-Carlo-Simulation aktivieren",
        "monteCarloSuccessRateMessage": "Das aktuelle Szenario hat eine Erfolgsquote von <strong>{successRate}%</strong>.",
        "helpModalWelcome": "Willkommen bei SquirrelPlan!",
        "helpModalSampleData": "Klicken Sie auf die Schaltfläche unten, um mit dem Laden einiger Beispieldaten zu beginnen.",
        "helpModalIntro": "Dieses kostenlose und quelloffene Tool hilft Ihnen bei der Planung und Visualisierung Ihrer finanziellen Zukunft.",
        "helpModalHowToUse": "Wie zu verwenden:",
        "helpModalStep1": "<strong>Finanzdaten:</strong> Geben Sie Ihre Vermögenswerte (z. B. Ersparnisse, Investitionen), Verbindlichkeiten (z. B. Kredite), monatlichen Einnahmen und monatlichen Ausgaben ein. Für Vermögenswerte und Verbindlichkeiten können Sie eine jährliche Rendite oder einen Zinssatz angeben. Für Einnahmen und Ausgaben können Sie eine jährliche Steigerung angeben.",
        "helpModalStep2": "<strong>Sparzuweisung:</strong> Legen Sie fest, wie Ihre überschüssigen Ersparnisse auf Ihre verschiedenen Anlageklassen verteilt werden. Sie können unterschiedliche Zuweisungsstrategien für verschiedene Lebensabschnitte einrichten.",
        "helpModalStep3": "<strong>Ruhestandsplanung:</strong> Geben Sie Ihr aktuelles Alter, das gesetzliche Rentenalter und Ihre geschätzte monatliche Nettorente vom Staat ein.",
        "helpModalStep4": "<strong>Erweiterte Einstellungen:</strong> Passen Sie die Simulation mit Parametern wie der erwarteten jährlichen Inflationsrate an. Sie können auch ein gewünschtes Frührentenalter und eine Entnahmerate für Ihre Investitionen im Ruhestand festlegen.",
        "helpModalStep5": "<strong>Simulation durchführen:</strong><ul><li><strong>Standard-Simulation:</strong> Führt eine einzelne Projektion basierend auf den von Ihnen angegebenen genauen Werten aus.</li><li><strong>Monte-Carlo-Simulation:</strong> Aktivieren Sie diese im Abschnitt \"Erweitert\", um Hunderte von Simulationen mit zufälligen jährlichen Renditen für Ihre Vermögenswerte durchzuführen. Dies hilft, die Wahrscheinlichkeit zu bewerten, mit der Sie Ihre finanziellen Ziele erreichen.</li></ul>",
        "helpModalResultsInfo": "Die Ergebnisse werden in einem Diagramm und einer Tabelle angezeigt und zeigen die Entwicklung Ihres Vermögens im Laufe der Zeit.",
        "helpModalButtonsInfo": "Mit den Schaltflächen oben rechts können Sie Ihre Daten als JSON-Datei importieren oder exportieren oder alle Felder leeren.",
        "helpModalPrivacy": "Datenschutz zuerst: Wir werden Ihre Daten niemals in irgendeiner Form speichern oder weitergeben.",
        "helpModalSourceCode": "Quellcode verfügbar unter: <a href=\"https://github.com/skapebolt/SquirrelPlan\">https://github.com/skapebolt/SquirrelPlan</a>",
        "nameLabel": "Name",
        "valueLabel": "Wert",
        "returnLabel": "Rendite (%)",
        "taxLabel": "Steuer (%)",
        "startLabel": "Start",
        "endLabel": "Ende",
        "withdrawalOrderLabel": "Reihenfolge",
        "interestRateLabel": "Zinssatz (%)",
        "frequencyLabel": "Häufigkeit",
        "indexedLabel": "Indexiert",
        "monthlyOption": "Monatlich",
        "yearlyOption": "Jährlich",
        "deleteAssetCategoryLabel": "Anlagekategorie löschen",
        "deleteLiabilityCategoryLabel": "Haftungskategorie löschen",
        "deleteIncomeCategoryLabel": "Einkommenskategorie löschen",
        "deleteExpenseCategoryLabel": "Ausgabenkategorie löschen",
        "deleteAllocationPeriodLabel": "Zuweisungszeitraum löschen",
        "startYearLabel": "Startjahr",
        "clearDataConfirmation": "Sind Sie sicher, dass Sie alle Daten löschen möchten?",
        "earlyRetirementMessage": "Sie können möglicherweise im Jahr <strong>{year}</strong> im Alter von <strong>{age}</strong> mit einem Nettovermögen von <strong>{netWorth}</strong> in den Vorruhestand gehen!",
        "pensionWithdrawalMessage": "Ihre erste jährliche Auszahlung bei Erreichen des Rentenalters würde <strong>{amount}</strong> ({rate}% von {netWorth}) betragen, oder <strong>{monthly}</strong> pro Monat.",
        "netWorthLabel": "Nettovermögen",
        "yearHeader": "Jahr",
        "ageHeader": "Alter",
        "ageLabel": "Alter",
        "netIncomeHeader": "Nettoeinkommen",
        "expensesHeader": "Ausgaben",
        "savingsCapacityHeader": "Sparkapazität",
        "savingsRateHeader": "Sparquote",
        "netWorthHeader": "Nettovermögen",
        "assetHeader": "{asset} (Vermögenswert)",
        "liabilityHeader": "{liability} (Verbindlichkeit)",
        "ownHome": "Eigenheim",
        "stocks": "Aktien",
        "bonds": "Anleihen",
        "savingsAccount": "Sparkonto",
        "mortgage": "Hypothek",
        "salary": "Gehalt",
        "livingExpenses": "Lebenshaltungskosten",
        "mortgageRepayment": "Hypothekenrückzahlung",
        "bigexpense1": "Große Ausgabe 1",
        "bigexpense2": "Große Ausgabe 2",
        "bigexpense3": "Große Ausgabe 3",
        "inflationTooltip": "Die durchschnittliche jährliche Preissteigerung. Dies wird verwendet, um den zukünftigen Wert des Geldes zu berechnen.",
        "currentAgeTooltip": "Ihr aktuelles Alter in Jahren.",
        "legalRetirementAgeTooltip": "Das Alter, in dem Sie eine staatliche Rente erhalten.",
        "monthlyPensionTooltip": "Die geschätzte monatliche Nettorente, die Sie von der Regierung erhalten werden.",
        "withdrawalRateTooltip": "Der Prozentsatz Ihres Gesamtvermögens, den Sie jährlich nach der Pensionierung abheben möchten (z.B. die 4%-Regel).",
        "earlyRetirementAgeTooltip": "Das Alter, in dem Sie planen, mit der Arbeit aufzuhören, falls es vor dem gesetzlichen Rentenalter liegt. Das Einkommen wird gestoppt, aber die Rente beginnt erst im gesetzlichen Rentenalter.",
        "enableMonteCarloTooltip": "Aktivieren Sie dies, um eine Monte-Carlo-Simulation durchzuführen, die mehrere Ergebnisse simuliert, um die Robustheit Ihres Plans zu testen.",
        "assetNameTooltip": "Ein eindeutiger Name für diese Kategorie.",
        "assetValueTooltip": "Der aktuelle Wert in Ihrer Währung.",
        "assetReturnTooltip": "Die erwartete jährliche Rendite auf dieses Vermögen nach Kosten.",
        "assetTaxTooltip": "Die jährliche Steuer auf die Rendite oder den Kapitalgewinn.",
        "assetStartYearTooltip": "Das Jahr, in dem diese Kategorie aktiv wird.",
        "assetEndYearTooltip": "Das Jahr, in dem diese Kategorie endet. Leer lassen, falls nicht zutreffend.",
        "assetWithdrawalOrderTooltip": "Die Reihenfolge der Auszahlung im Falle eines Defizits oder nach der Pensionierung (1 = zuerst, 99 = zuletzt).",
        "liabilityNameTooltip": "Ein eindeutiger Name für diese Kategorie.",
        "liabilityValueTooltip": "Der aktuelle Wert in Ihrer Währung.",
        "liabilityStartYearTooltip": "Das Jahr, in dem diese Kategorie aktiv wird.",
        "liabilityEndYearTooltip": "Das Jahr, in dem diese Kategorie endet. Leer lassen, falls nicht zutreffend.",
        "liabilityInterestRateTooltip": "Der jährliche Zinssatz des Darlehens. Wenn leer, wird die Verbindlichkeit linear abnehmen.",
        "incomeNameTooltip": "Ein eindeutiger Name für diese Kategorie.",
        "incomeValueTooltip": "Der aktuelle Wert in Ihrer Währung.",
        "incomeFrequencyTooltip": "Wie oft dieses Einkommen anfällt.",
        "incomeIndexedTooltip": "Aktivieren Sie dieses Kontrollkästchen, wenn dieser Betrag jährlich mit der Inflation steigen soll.",
        "incomeStartYearTooltip": "Das Jahr, in dem diese Kategorie aktiv wird.",
        "incomeEndYearTooltip": "Das Jahr, in dem diese Kategorie endet. Leer lassen, falls nicht zutreffend.",
        "expenseNameTooltip": "Ein eindeutiger Name für diese Kategorie.",
        "expenseValueTooltip": "Der aktuelle Wert in Ihrer Währung.",
        "expenseFrequencyTooltip": "Wie oft diese Ausgabe anfällt.",
        "expenseIndexedTooltip": "Aktivieren Sie dieses Kontrollkästchen, wenn dieser Betrag jährlich mit der Inflation steigen soll.",
        "expenseStartYearTooltip": "Das Jahr, in dem diese Kategorie aktiv wird.",
        "expenseEndYearTooltip": "Das Jahr, in dem diese Kategorie endet. Leer lassen, falls nicht zutreffend.",
        "languageAlreadySelected": "Diese Sprache ist bereits ausgewählt.",
        "notificationTitle": "Benachrichtigung",
        "endYearBeforeStartYearError": "Endjahr kann nicht vor Startjahr liegen.",
        "retirementAgeBeforeCurrentAgeError": "Rentenalter kann nicht kleiner sein als aktuelles Alter.",
        "autoRebalanceLabel": "Automatisches Auswuchten",
        "autoRebalanceTooltip": "Wenn diese Option aktiviert ist, werden die prozentualen Anteile der Vermögenswerte während der gesamten Simulation durch automatisches Auswuchten beibehalten.",
        "portraitModeMessage": "Bitte drehen Sie Ihr Gerät in den Querformatmodus für die beste Erfahrung.",
        "autoSaveLabel": "Daten auf diesem Gerät automatisch speichern",
        "autoSaveTooltip": "Wenn diese Option aktiviert ist, werden Ihre Finanzdaten automatisch im lokalen Speicher Ihres Browsers gespeichert. Deaktivieren Sie diese Option, wenn Sie Bedenken hinsichtlich des Datenschutzes haben.",
        "loadSampleDataButton": "Beispieldaten laden",
        "total": "Gesamt",
        "sampleDataModalTitle": "Wählen Sie eine Lebensphase",
        "recentGraduate": "Kürzlich graduiert",
        "earlyCareer": "Frühe Karriere",
        "midCareer": "Mitte der Karriere",
        "lateCareer": "Späte Karriere",
        "onboardingWelcomeTitle": "Willkommen bei SquirrelPlan!",
        "onboardingIntro": "Entdecken Sie, wie kleine Änderungen heute zu erheblichem Vermögenswachstum im Laufe der Zeit führen können. Dieses Tool hilft Ihnen, Ihr Vermögen in die Zukunft zu projizieren. Passen Sie Ihre monatlichen Ersparnisse an, um zu sehen, wie sich dies auf Ihre 30-Jahres-Projektion auswirkt.",
        "onboardingSliderLabel": "Monatliche Ersparnisse",
        "onboardingStartBlank": "Mit einem leeren Plan beginnen",
        "onboardingNext": "Nächste",
        "onboardingNextButtonExplanation": "Klicken Sie auf 'Weiter', um loszulegen: Sie werden gebeten, zwischen einem voreingestellten Plan und einem leeren Plan zu wählen.",
        "newBlankPlanButton": "Neuer leerer Plan",
        "plansModalTitle": "Wählen Sie einen Plan",
        "presetPlansTitle": "Voreingestellte Pläne",
        "userPlansTitle": "Ihre Pläne",
        "noUserPlans": "Sie haben noch keine Pläne erstellt.",
        "onboardingPrevious": "Bisherige",
        "projectedWealthLabel": "Projiziertes Vermögen",
        "plansButton": "Pläne",
        "actionsButton": "Aktionen",
        "clearPlanButton": "Plan löschen",
        "renamePlanButton": "Umbenennen",
        "duplicatePlanButton": "Duplizieren",
        "deletePlanButton": "Löschen",
        "assetDeletionWarning": "Warnung: Sie haben ein Asset ('{assetName}') gelöscht, das Teil Ihrer Sparzuweisung war. Bitte überprüfen Sie Ihre Zuweisung.",
        "enterNewPlanNamePrompt": "Geben Sie einen neuen Namen für den Plan ein:",
        "deletePlanConfirmation": "Sind Sie sicher, dass Sie den Plan '{planName}' löschen möchten?",
        "copyOf": "Kopie von ",
        "newPlanName": "Neuer Plan",
        "planNameExistsError": "Ein Plan mit diesem Namen existiert bereits.",
        "cannotDeleteLastPlanError": "Sie können den letzten Plan nicht löschen.",
        "savePresetAsNewPlanPrompt": "Sie haben eine Voreinstellung bearbeitet. Möchten Sie Ihre Änderungen als neuen Plan speichern? Bitte geben Sie einen Namen für den neuen Plan ein."
    },
    "en": {
        "pageTitle": "SquirrelPlan",
        "languageSelector": "Language",
        "navbarBrand": "SquirrelPlan",
        "darkModeLabel": "Dark mode",
        "importButton": "Import",
        "exportButton": "Export",
        "clearButton": "Clear",
        "settingsTitle": "Settings",
        "inflationLabel": "Inflation (%)",
        "financialDataTitle": "Financial Data",
        "assetsAccordionButton": "Assets",
        "newAssetButton": "New Asset Class",
        "liabilitiesAccordionButton": "Liabilities",
        "newLiabilityButton": "New Liability Class",
        "incomeAccordionButton": "Income",
        "newIncomeButton": "New Income Category",
        "expensesAccordionButton": "Expenses",
        "newExpenseButton": "New Expense Category",
        "savingsAllocationAccordionButton": "Savings Allocation",
        "newAllocationPeriodButton": "New Allocation Period",
        "retirementPlanningAccordionButton": "Retirement Planning",
        "currentAgeLabel": "Current Age",
        "legalRetirementAgeLabel": "Legal Retirement Age",
        "monthlyPensionLabel": "Monthly Pension (net)",
        "withdrawalRateLabel": "Withdrawal Rate (%)",
        "runStandardSimulationButton": "Run Standard Simulation",
        "runMonteCarloSimulationButton": "Run Monte Carlo Simulation",
        "resultsTitle": "Results",
        "helpModalTitle": "Help",
        "advancedAccordionButton": "Advanced",
        "earlyRetirementAgeLabel": "Early Retirement Age",
        "enableMonteCarloLabel": "Enable Monte Carlo Simulation",
        "monteCarloSuccessRateMessage": "The current scenario has a success rate of <strong>{successRate}%</strong>.",
        "helpModalWelcome": "Welcome to SquirrelPlan!",
        "helpModalSampleData": "Click the button below to get you started by loading some sample data.",
        "helpModalIntro": "This free and open source tool helps you plan and visualize your financial future.",
        "helpModalHowToUse": "How to use:",
        "helpModalStep1": "<strong>Financial Data:</strong> Fill in your assets (e.g., savings, investments), liabilities (e.g., loans), monthly income, and monthly expenses. For assets and liabilities, you can specify an annual return or interest rate. For income and expenses, you can specify an annual increase.",
        "helpModalStep2": "<strong>Savings Allocation:</strong> Define how your surplus savings are allocated to your different asset classes. You can set up different allocation strategies for different periods of your life.",
        "helpModalStep3": "<strong>Retirement Planning:</strong> Enter your current age, the legal retirement age, and your estimated net monthly pension from the government.",
        "helpModalStep4": "<strong>Advanced Settings:</strong> Fine-tune the simulation with parameters like the expected annual inflation rate. You can also set a desired early retirement age and a withdrawal rate for your investments during retirement.",
        "helpModalStep5": "<strong>Run Simulation:</strong><ul><li><strong>Standard Simulation:</strong> Runs a single projection based on the exact values you provided.</li><li><strong>Monte Carlo Simulation:</strong> Enable this in the \"Advanced\" section to run hundreds of simulations with randomized annual returns for your assets. This helps to assess the probability of achieving your financial goals.</li></ul>",
        "helpModalResultsInfo": "The results are displayed in a chart and a table, showing the evolution of your wealth over time.",
        "helpModalButtonsInfo": "With the buttons at the top right, you can import or export your data as a JSON file, or clear all fields.",
        "helpModalPrivacy": "Privacy first: We will never store or share your data in any way, shape or form.",
        "helpModalSourceCode": "Source code availaible at: <a href=\"https://github.com/skapebolt/SquirrelPlan\">https://github.com/skapebolt/SquirrelPlan</a>",
        "nameLabel": "Name",
        "valueLabel": "Value",
        "returnLabel": "Return (%)",
        "taxLabel": "Tax (%)",
        "startLabel": "Start",
        "endLabel": "End",
        "withdrawalOrderLabel": "Order",
        "interestRateLabel": "Interest Rate (%)",
        "frequencyLabel": "Frequency",
        "indexedLabel": "Indexed",
        "monthlyOption": "Monthly",
        "yearlyOption": "Yearly",
        "deleteAssetCategoryLabel": "Delete asset category",
        "deleteLiabilityCategoryLabel": "Delete liability category",
        "deleteIncomeCategoryLabel": "Delete income category",
        "deleteExpenseCategoryLabel": "Delete expense category",
        "deleteAllocationPeriodLabel": "Delete allocation period",
        "startYearLabel": "Start Year",
        "clearDataConfirmation": "Are you sure you want to clear all data?",
        "earlyRetirementMessage": "You may be able to retire early in <strong>{year}</strong> at the age of <strong>{age}</strong> with a net worth of <strong>{netWorth}</strong>!",
        "pensionWithdrawalMessage": "Your first annual withdrawal upon reaching retirement age would be <strong>{amount}</strong> ({rate}% of {netWorth}), or <strong>{monthly}</strong> per month.",
        "netWorthLabel": "Net Worth",
        "yearHeader": "Year",
        "ageHeader": "Age",
        "ageLabel": "Age",
        "netIncomeHeader": "Net Income",
        "expensesHeader": "Expenses",
        "savingsCapacityHeader": "Savings Capacity",
        "savingsRateHeader": "Savings Rate",
        "netWorthHeader": "Net Worth",
        "assetHeader": "{asset} (Asset)",
        "liabilityHeader": "{liability} (Liability)",
        "ownHome": "Own Home",
        "stocks": "Stocks",
        "bonds": "Bonds",
        "savingsAccount": "Savings Account",
        "mortgage": "Mortgage",
        "salary": "Salary",
        "livingExpenses": "Living Expenses",
        "mortgageRepayment": "Mortgage Repayment",
        "bigexpense1": "Big Expense 1",
        "bigexpense2": "Big Expense 2",
        "bigexpense3": "Big Expense 3",
        "inflationTooltip": "The average annual increase in prices. This is used to calculate the future value of money.",
        "currentAgeTooltip": "Your current age in years.",
        "legalRetirementAgeTooltip": "The age at which you will start receiving a government pension.",
        "monthlyPensionTooltip": "The estimated net monthly pension you will receive from the government.",
        "withdrawalRateTooltip": "The percentage of your total assets that you plan to withdraw annually after retirement (e.g., the 4% rule).",
        "earlyRetirementAgeTooltip": "The age you plan to stop working, if earlier than the legal retirement age. Income will stop, but pension will only start at the legal retirement age.",
        "enableMonteCarloTooltip": "Enable this to run a Monte Carlo simulation, which simulates multiple outcomes to test the robustness of your plan.",
        "assetNameTooltip": "A unique name for this category.",
        "assetValueTooltip": "The current value in your currency.",
        "assetReturnTooltip": "The expected annual return on this asset, after costs.",
        "assetTaxTooltip": "The annual tax on the return or capital gain.",
        "assetStartYearTooltip": "The year this category becomes active.",
        "assetEndYearTooltip": "The year this category stops. Leave empty if not applicable.",
        "assetWithdrawalOrderTooltip": "The withdrawal order in case of a deficit or after retirement (1 = first, 99 = last).",
        "liabilityNameTooltip": "A unique name for this category.",
        "liabilityValueTooltip": "The current value in your currency.",
        "liabilityStartYearTooltip": "The year this category becomes active.",
        "liabilityEndYearTooltip": "The year this category stops. Leave empty if not applicable.",
        "liabilityInterestRateTooltip": "The annual interest rate of the loan. If empty, the liability will decrease linearly.",
        "incomeNameTooltip": "A unique name for this category.",
        "incomeValueTooltip": "The current value in your currency.",
        "incomeFrequencyTooltip": "How often this income occurs.",
        "incomeIndexedTooltip": "Check if this amount should increase annually with inflation.",
        "incomeStartYearTooltip": "The year this category becomes active.",
        "incomeEndYearTooltip": "The year this category stops. Leave empty if not applicable.",
        "expenseNameTooltip": "A unique name for this category.",
        "expenseValueTooltip": "The current value in your currency.",
        "expenseFrequencyTooltip": "How often this expense occurs.",
        "expenseIndexedTooltip": "Check if this amount should increase annually with inflation.",
        "expenseStartYearTooltip": "The year this category becomes active.",
        "expenseEndYearTooltip": "The year this category stops. Leave empty if not applicable.",
        "languageAlreadySelected": "This language is already selected.",
        "notificationTitle": "Notification",
        "endYearBeforeStartYearError": "End year cannot be before start year.",
        "retirementAgeBeforeCurrentAgeError": "Retirement age cannot be less than current age.",
        "autoRebalanceLabel": "Automatic rebalance",
        "autoRebalanceTooltip": "If checked, the asset allocation percentages will be maintained throughout the simulation by automatically rebalancing the portfolio.",
        "portraitModeMessage": "Please turn your device to landscape mode for the best experience.",
        "autoSaveLabel": "Automatically save data on this device",
        "autoSaveTooltip": "When enabled, your financial data is automatically saved to your browser's local storage. Disable this if you have privacy concerns.",
        "loadSampleDataButton": "Load Sample Data",
        "total": "Total",
        "sampleDataModalTitle": "Select a life stage",
        "recentGraduate": "Recent Graduate",
        "earlyCareer": "Early Career",
        "midCareer": "Mid Career",
        "lateCareer": "Late Career",
        "plansButton": "Plans",
        "actionsButton": "Actions",
        "clearPlanButton": "Clear Plan",
        "renamePlanButton": "Rename",
        "duplicatePlanButton": "Duplicate",
        "deletePlanButton": "Delete",
        "onboardingWelcomeTitle": "Welcome to SquirrelPlan!",
        "onboardingIntro": "Discover how small changes today can lead to significant wealth growth over time. This tool helps you project your wealth into the future. Adjust your monthly savings to see how it impacts your 30-year projection.",
        "onboardingSliderLabel": "Monthly Savings",
        "onboardingStartBlank": "Start with a Blank Plan",
        "onboardingNext": "Next",
        "onboardingNextButtonExplanation": "Click 'Next' to get started: you will be asked to choose between a preset plan or a blank one.",
        "newBlankPlanButton": "New Blank Plan",
        "plansModalTitle": "Choose a Plan",
        "presetPlansTitle": "Preset Plans",
        "userPlansTitle": "Your Plans",
        "noUserPlans": "You haven't created any plans yet.",
        "onboardingPrevious": "Previous",
        "projectedWealthLabel": "Projected Wealth",
        "assetDeletionWarning": "Warning: You deleted an asset ('{assetName}') that was part of your savings allocation. Please review your allocation.",
        "enterNewPlanNamePrompt": "Enter a new name for the plan:",
        "deletePlanConfirmation": "Are you sure you want to delete the plan '{planName}'?",
        "copyOf": "Copy of ",
        "newPlanName": "New Plan",
        "planNameExistsError": "A plan with this name already exists.",
        "cannotDeleteLastPlanError": "You cannot delete the last plan.",
        "savePresetAsNewPlanPrompt": "You've edited a preset. Would you like to save your changes as a new plan? Please enter a name for the new plan."
    },
    "es": {
        "pageTitle": "SquirrelPlan",
        "languageSelector": "Idioma",
        "navbarBrand": "SquirrelPlan",
        "darkModeLabel": "Modo oscuro",
        "importButton": "Importar",
        "exportButton": "Exportar",
        "clearButton": "Limpiar",
        "settingsTitle": "Configuración",
        "inflationLabel": "Inflación (%)",
        "financialDataTitle": "Datos Financieros",
        "assetsAccordionButton": "Activos",
        "newAssetButton": "Nueva clase de activos",
        "liabilitiesAccordionButton": "Pasivos",
        "newLiabilityButton": "Nueva clase de pasivos",
        "incomeAccordionButton": "Ingresos",
        "newIncomeButton": "Nueva categoría de ingresos",
        "expensesAccordionButton": "Gastos",
        "newExpenseButton": "Nueva categoría de gastos",
        "savingsAllocationAccordionButton": "Asignación de Ahorros",
        "newAllocationPeriodButton": "Nuevo período de asignación",
        "retirementPlanningAccordionButton": "Planificación de la Jubilación",
        "currentAgeLabel": "Edad actual",
        "legalRetirementAgeLabel": "Edad Legal de Jubilación",
        "monthlyPensionLabel": "Pensión mensual (neta)",
        "withdrawalRateLabel": "Tasa de retiro (%)",
        "runStandardSimulationButton": "Ejecutar Simulación Estándar",
        "runMonteCarloSimulationButton": "Ejecutar Simulación Monte Carlo",
        "resultsTitle": "Resultados",
        "helpModalTitle": "Ayuda",
        "advancedAccordionButton": "Avanzado",
        "earlyRetirementAgeLabel": "Edad de Jubilación Temprana",
        "enableMonteCarloLabel": "Habilitar Simulación Monte Carlo",
        "monteCarloSuccessRateMessage": "El escenario actual tiene una tasa de éxito de <strong>{successRate}%</strong>.",
        "helpModalWelcome": "¡Bienvenido a SquirrelPlan!",
        "helpModalSampleData": "Haga clic en el botón de abajo para empezar cargando algunos datos de ejemplo.",
        "helpModalIntro": "Esta herramienta gratuita y de código abierto le ayuda a planificar y visualizar su futuro financiero.",
        "helpModalHowToUse": "Cómo utilizar:",
        "helpModalStep1": "<strong>Datos Financieros:</strong> Rellene sus activos (p. ej., ahorros, inversiones), pasivos (p. ej., préstamos), ingresos mensuales y gastos mensuales. Para activos y pasivos, puede especificar un rendimiento anual o una tasa de interés. Para ingresos y gastos, puede especificar un aumento anual.",
        "helpModalStep2": "<strong>Asignación de Ahorros:</strong> Defina cómo se asignan sus ahorros excedentes a sus diferentes clases de activos. Puede configurar diferentes estrategias de asignación para diferentes períodos de su vida.",
        "helpModalStep3": "<strong>Planificación de la Jubilación:</strong> Ingrese su edad actual, la edad legal de jubilación y su pensión mensual neta estimada del gobierno.",
        "helpModalStep4": "<strong>Configuraciones Avanzadas:</strong> Ajuste la simulación con parámetros como la tasa de inflación anual esperada. También puede establecer una edad de jubilación anticipada deseada y una tasa de retiro para sus inversiones durante la jubilación.",
        "helpModalStep5": "<strong>Ejecutar Simulación:</strong><ul><li><strong>Simulación Estándar:</strong> Ejecuta una única proyección basada en los valores exactos que proporcionó.</li><li><strong>Simulación de Monte Carlo:</strong> Habilite esto en la sección \"Avanzado\" para ejecutar cientos de simulaciones con rendimientos anuales aleatorios para sus activos. Esto ayuda a evaluar la probabilidad de alcanzar sus metas financieras.</li></ul>",
        "helpModalResultsInfo": "Los resultados se muestran en un gráfico y una tabla, que muestran la evolución de su patrimonio a lo largo del tiempo.",
        "helpModalButtonsInfo": "Con los botones en la parte superior derecha, puede importar o exportar sus datos como un archivo JSON, o borrar todos los campos.",
        "helpModalPrivacy": "La privacidad es lo primero: nunca almacenaremos ni compartiremos sus datos de ninguna manera.",
        "helpModalSourceCode": "Código fuente disponible en: <a href=\"https://github.com/skapebolt/SquirrelPlan\">https://github.com/skapebolt/SquirrelPlan</a>",
        "nameLabel": "Nombre",
        "valueLabel": "Valor",
        "returnLabel": "Rendimiento (%)",
        "taxLabel": "Impuesto (%)",
        "startLabel": "Inicio",
        "endLabel": "Fin",
        "withdrawalOrderLabel": "Orden",
        "interestRateLabel": "Tasa de Interés (%)",
        "frequencyLabel": "Frecuencia",
        "indexedLabel": "Indexado",
        "monthlyOption": "Mensual",
        "yearlyOption": "Anual",
        "deleteAssetCategoryLabel": "Eliminar categoría de activo",
        "deleteLiabilityCategoryLabel": "Eliminar categoría de pasivo",
        "deleteIncomeCategoryLabel": "Eliminar categoría de ingresos",
        "deleteExpenseCategoryLabel": "Eliminar categoría de gastos",
        "deleteAllocationPeriodLabel": "Eliminar período de asignación",
        "startYearLabel": "Año de inicio",
        "clearDataConfirmation": "¿Está seguro de que desea borrar todos los datos?",
        "earlyRetirementMessage": "¡Es posible que pueda jubilarse anticipadamente en <strong>{year}</strong> a la edad de <strong>{age}</strong> con un patrimonio neto de <strong>{netWorth}</strong>!",
        "pensionWithdrawalMessage": "Su primer retiro anual al alcanzar la edad de jubilación sería de <strong>{amount}</strong> ({rate}% de {netWorth}), o <strong>{monthly}</strong> por mes.",
        "netWorthLabel": "Patrimonio neto",
        "yearHeader": "Año",
        "ageHeader": "Edad",
        "ageLabel": "Edad",
        "netIncomeHeader": "Ingresos netos",
        "expensesHeader": "Gastos",
        "savingsCapacityHeader": "Capacidad de ahorro",
        "savingsRateHeader": "Tasa de ahorro",
        "netWorthHeader": "Patrimonio neto",
        "assetHeader": "{asset} (Activo)",
        "liabilityHeader": "{liability} (Pasivo)",
        "ownHome": "Vivienda propia",
        "stocks": "Acciones",
        "bonds": "Bonos",
        "savingsAccount": "Cuenta de ahorros",
        "mortgage": "Hipoteca",
        "salary": "Salario",
        "livingExpenses": "Gastos de manutención",
        "mortgageRepayment": "Pago de la hipoteca",
        "bigexpense1": "Gasto Grande 1",
        "bigexpense2": "Gasto Grande 2",
        "bigexpense3": "Gasto Grande 3",
        "inflationTooltip": "El aumento anual promedio de los precios. Se utiliza para calcular el valor futuro del dinero.",
        "currentAgeTooltip": "Su edad actual en años.",
        "legalRetirementAgeTooltip": "La edad a la que comenzará a recibir una pensión del gobierno.",
        "monthlyPensionTooltip": "La pensión mensual neta estimada que recibirá del gobierno.",
        "withdrawalRateTooltip": "El porcentaje de sus activos totales que planea retirar anualmente después de la jubilación (por ejemplo, la regla del 4%).",
        "earlyRetirementAgeTooltip": "La edad a la que planea dejar de trabajar, si es anterior a la edad legal de jubilación. Los ingresos se detendrán, pero la pensión solo comenzará a la edad legal de jubilación.",
        "enableMonteCarloTooltip": "Habilite esto para ejecutar una simulación de Monte Carlo, que simula múltiples resultados para probar la solidez de su plan.",
        "assetNameTooltip": "Un nombre único para esta categoría.",
        "assetValueTooltip": "El valor actual en su moneda.",
        "assetReturnTooltip": "El rendimiento anual esperado de este activo, después de costos.",
        "assetTaxTooltip": "El impuesto anual sobre el rendimiento o la ganancia de capital.",
        "assetStartYearTooltip": "El año en que esta categoría se vuelve activa.",
        "assetEndYearTooltip": "El año en que esta categoría se detiene. Deje en blanco si no corresponde.",
        "assetWithdrawalOrderTooltip": "El orden de retiro en caso de déficit o después de la jubilación (1 = primero, 99 = último).",
        "liabilityNameTooltip": "Un nombre único para esta categoría.",
        "liabilityValueTooltip": "El valor actual en su moneda.",
        "liabilityStartYearTooltip": "El año en que esta categoría se vuelve activa.",
        "liabilityEndYearTooltip": "El año en que esta categoría se detiene. Deje en blanco si no corresponde.",
        "liabilityInterestRateTooltip": "La tasa de interés anual del préstamo. Si está vacío, la responsabilidad disminuirá linealmente.",
        "incomeNameTooltip": "Un nombre único para esta categoría.",
        "incomeValueTooltip": "El valor actual en su moneda.",
        "incomeFrequencyTooltip": "Con qué frecuencia se produce este ingreso.",
        "incomeIndexedTooltip": "Marque si esta cantidad debe aumentar anualmente con la inflación.",
        "incomeStartYearTooltip": "El año en que esta categoría se vuelve activa.",
        "incomeEndYearTooltip": "El año en que esta categoría se detiene. Deje en blanco si no corresponde.",
        "expenseNameTooltip": "Un nombre único para esta categoría.",
        "expenseValueTooltip": "El valor actual en su moneda.",
        "expenseFrequencyTooltip": "Con qué frecuencia se produce este gasto.",
        "expenseIndexedTooltip": "Marque si esta cantidad debe aumentar anualmente con la inflación.",
        "expenseStartYearTooltip": "El año en que esta categoría se vuelve activa.",
        "expenseEndYearTooltip": "El año en que esta categoría se detiene. Deje en blanco si no corresponde.",
        "languageAlreadySelected": "Este idioma ya está seleccionado.",
        "notificationTitle": "Notificación",
        "endYearBeforeStartYearError": "El año de fin no puede ser anterior al año de inicio.",
        "retirementAgeBeforeCurrentAgeError": "La edad de jubilación no puede ser menor que la edad actual.",
        "autoRebalanceLabel": "Rebalanceo automático",
        "autoRebalanceTooltip": "Si está marcada, los porcentajes de asignación de activos se mantendrán a lo largo de la simulación mediante el rebalanceo automático de la cartera.",
        "portraitModeMessage": "Por favor, gire su dispositivo a modo horizontal para una mejor experiencia.",
        "autoSaveLabel": "Guardar datos automáticamente en este dispositivo",
        "autoSaveTooltip": "Cuando está habilitado, sus datos financieros se guardan automáticamente en el almacenamiento local de su navegador. Deshabilite esto si tiene preocupaciones de privacidad.",
        "loadSampleDataButton": "Cargar datos de ejemplo",
        "total": "Total",
        "sampleDataModalTitle": "Seleccione una etapa de la vida",
        "recentGraduate": "Recién graduado",
        "earlyCareer": "Carrera temprana",
        "midCareer": "Mitad de carrera",
        "lateCareer": "Carrera tardía",
        "plansButton": "Planes",
        "actionsButton": "Acciones",
        "clearPlanButton": "Limpiar plan",
        "renamePlanButton": "Renombrar",
        "duplicatePlanButton": "Duplicar",
        "deletePlanButton": "Eliminar",
        "onboardingWelcomeTitle": "¡Bienvenido a SquirrelPlan!",
        "onboardingIntro": "Descubra cómo pequeños cambios hoy pueden conducir a un importante crecimiento de la riqueza con el tiempo. Esta herramienta le ayuda a proyectar su patrimonio en el futuro. Ajuste sus ahorros mensuales para ver cómo afecta su proyección a 30 años.",
        "onboardingSliderLabel": "Ahorros mensuales",
        "onboardingStartBlank": "Comenzar con un plan en blanco",
        "onboardingNext": "Siguiente",
        "onboardingNextButtonExplanation": "Haga clic en 'Siguiente' para comenzar: se le pedirá que elija entre un plan preestablecido o uno en blanco.",
        "newBlankPlanButton": "Nuevo plan en blanco",
        "plansModalTitle": "Elige un plan",
        "presetPlansTitle": "Planes preestablecidos",
        "userPlansTitle": "Tus planes",
        "noUserPlans": "Aún no has creado ningún plan.",
        "onboardingPrevious": "Anterior",
        "projectedWealthLabel": "Riqueza proyectada",
        "assetDeletionWarning": "Advertencia: Ha eliminado un activo ('{assetName}') que formaba parte de su asignación de ahorros. Revise su asignación.",
		"enterNewPlanNamePrompt": "Introduzca un nuevo nombre para el plan:",
		"deletePlanConfirmation": "¿Está seguro de que desea eliminar el plan '{planName}'?",
		"copyOf": "Copia de ",
		"newPlanName": "Nuevo plan",
		"planNameExistsError": "Ya existe un plan con este nombre.",
		"cannotDeleteLastPlanError": "No puede eliminar el último plan.",
		"savePresetAsNewPlanPrompt": "Ha editado un preajuste. ¿Desea guardar los cambios como un nuevo plan? Introduzca un nombre para el nuevo plan."
    },
    "fr": {
        "pageTitle": "SquirrelPlan",
        "languageSelector": "Langue",
        "navbarBrand": "SquirrelPlan",
        "darkModeLabel": "Mode sombre",
        "importButton": "Importer",
        "exportButton": "Exporter",
        "clearButton": "Effacer",
        "settingsTitle": "Paramètres",
        "inflationLabel": "Inflation (%)",
        "financialDataTitle": "Données Financières",
        "assetsAccordionButton": "Actifs",
        "newAssetButton": "Nouvelle classe d'actifs",
        "liabilitiesAccordionButton": "Passifs",
        "newLiabilityButton": "Nouvelle classe de passifs",
        "incomeAccordionButton": "Revenus",
        "newIncomeButton": "Nouvelle catégorie de revenus",
        "expensesAccordionButton": "Dépenses",
        "newExpenseButton": "Nouvelle catégorie de dépenses",
        "savingsAllocationAccordionButton": "Allocation de l'Épargne",
        "newAllocationPeriodButton": "Nouvelle période d'allocation",
        "retirementPlanningAccordionButton": "Planification de la Retraite",
        "currentAgeLabel": "Âge actuel",
        "legalRetirementAgeLabel": "Âge légal de la retraite",
        "monthlyPensionLabel": "Pension mensuelle (nette)",
        "withdrawalRateLabel": "Taux de retrait (%)",
        "runStandardSimulationButton": "Lancer la simulation standard",
        "runMonteCarloSimulationButton": "Lancer la simulation Monte Carlo",
        "resultsTitle": "Résultats",
        "helpModalTitle": "Aide",
        "advancedAccordionButton": "Avancé",
        "earlyRetirementAgeLabel": "Âge de la retraite anticipée",
        "enableMonteCarloLabel": "Activer la simulation Monte Carlo",
        "monteCarloSuccessRateMessage": "Le scénario actuel a un taux de réussite de <strong>{successRate}%</strong>.",
        "helpModalWelcome": "Bienvenue sur SquirrelPlan!",
        "helpModalSampleData": "Cliquez sur le bouton ci-dessous pour commencer par charger des exemples de données.",
        "helpModalIntro": "Cet outil gratuit et open source vous aide à planifier et à visualiser votre avenir financier.",
        "helpModalHowToUse": "Comment utiliser :",
        "helpModalStep1": "<strong>Données financières :</strong> Remplissez vos actifs (par exemple, épargne, investissements), vos passifs (par exemple, prêts), vos revenus mensuels et vos dépenses mensuelles. Pour les actifs et les passifs, vous pouvez spécifier un rendement annuel ou un taux d'intérêt. Pour les revenus et les dépenses, vous pouvez spécifier une augmentation annuelle.",
        "helpModalStep2": "<strong>Allocation de l'épargne :</strong> Définissez comment votre épargne excédentaire est allouée à vos différentes classes d'actifs. Vous pouvez configurer différentes stratégies d'allocation pour différentes périodes de votre vie.",
        "helpModalStep3": "<strong>Planification de la retraite :</strong> Saisissez votre âge actuel, l'âge légal de la retraite et votre pension mensuelle nette estimée du gouvernement.",
        "helpModalStep4": "<strong>Paramètres avancés :</strong> Affinez la simulation avec des paramètres tels que le taux d'inflation annuel prévu. Vous pouvez également définir un âge de retraite anticipée souhaité et un taux de retrait pour vos investissements pendant la retraite.",
        "helpModalStep5": "<strong>Lancer la simulation :</strong><ul><li><strong>Simulation standard :</strong> Exécute une projection unique basée sur les valeurs exactes que vous avez fournies.</li><li><strong>Simulation Monte-Carlo :</strong> Activez cette option dans la section \"Avancé\" pour exécuter des centaines de simulations avec des rendements annuels aléatoires pour vos actifs. Cela permet d'évaluer la probabilité d'atteindre vos objectifs financiers.</li></ul>",
        "helpModalResultsInfo": "Les résultats sont affichés dans un graphique et un tableau, montrant l'évolution de votre patrimoine dans le temps.",
        "helpModalButtonsInfo": "Avec les boutons en haut à droite, vous pouvez importer ou exporter vos données sous forme de fichier JSON, ou effacer tous les champs.",
        "helpModalPrivacy": "La confidentialité d'abord : nous ne stockerons ni ne partagerons jamais vos données de quelque manière que ce soit.",
        "helpModalSourceCode": "Code source disponible sur: <a href=\"https://github.com/skapebolt/SquirrelPlan\">https://github.com/skapebolt/SquirrelPlan</a>",
        "nameLabel": "Nom",
        "valueLabel": "Valeur",
        "returnLabel": "Rendement (%)",
        "taxLabel": "Impôt (%)",
        "startLabel": "Début",
        "endLabel": "Fin",
        "withdrawalOrderLabel": "Ordre",
        "interestRateLabel": "Taux d'Intérêt (%)",
        "frequencyLabel": "Fréquence",
        "indexedLabel": "Indexé",
        "monthlyOption": "Mensuel",
        "yearlyOption": "Annuel",
        "deleteAssetCategoryLabel": "Supprimer la catégorie d'actifs",
        "deleteLiabilityCategoryLabel": "Supprimer la catégorie de passifs",
        "deleteIncomeCategoryLabel": "Supprimer la catégorie de revenus",
        "deleteExpenseCategoryLabel": "Supprimer la catégorie de dépenses",
        "deleteAllocationPeriodLabel": "Supprimer la période d'allocation",
        "startYearLabel": "Année de début",
        "clearDataConfirmation": "Êtes-vous sûr de vouloir effacer toutes les données ?",
        "earlyRetirementMessage": "Vous pourriez être en mesure de prendre une retraite anticipée en <strong>{year}</strong> à l'âge de <strong>{age}</strong> avec une valeur nette de <strong>{netWorth}</strong> !",
        "pensionWithdrawalMessage": "Votre premier retrait annuel à l'âge de la retraite serait de <strong>{amount}</strong> ({rate}% de {netWorth}), ou <strong>{monthly}</strong> par mois.",
        "netWorthLabel": "Valeur nette",
        "yearHeader": "Année",
        "ageHeader": "Âge",
        "ageLabel": "Âge",
        "netIncomeHeader": "Revenu net",
        "expensesHeader": "Dépenses",
        "savingsCapacityHeader": "Capacité d'épargne",
        "savingsRateHeader": "Taux d'épargne",
        "netWorthHeader": "Valeur nette",
        "assetHeader": "{asset} (Actif)",
        "liabilityHeader": "{liability} (Passif)",
        "ownHome": "Propre maison",
        "stocks": "Actions",
        "bonds": "Obligations",
        "savingsAccount": "Compte d'épargne",
        "mortgage": "Hypothèque",
        "salary": "Salaire",
        "livingExpenses": "Frais de subsistance",
        "mortgageRepayment": "Remboursement de l'hypothèque",
        "bigexpense1": "Grosse Dépense 1",
        "bigexpense2": "Grosse Dépense 2",
        "bigexpense3": "Grosse Dépense 3",
        "inflationTooltip": "L'augmentation annuelle moyenne des prix. Ceci est utilisé pour calculer la valeur future de l'argent.",
        "currentAgeTooltip": "Votre âge actuel en années.",
        "legalRetirementAgeTooltip": "L'âge auquel vous commencerez à recevoir une pension du gouvernement.",
        "monthlyPensionTooltip": "La pension mensuelle nette estimée que vous recevrez du gouvernement.",
        "withdrawalRateTooltip": "Le pourcentage de votre patrimoine total que vous prévoyez de retirer annuellement après la retraite (par exemple, la règle des 4%).",
        "earlyRetirementAgeTooltip": "L'âge auquel vous prévoyez d'arrêter de travailler, s'il est antérieur à l'âge légal de la retraite. Le revenu s'arrêtera, mais la pension ne commencera qu'à l'âge légal de la retraite.",
        "enableMonteCarloTooltip": "Activez cette option pour exécuter une simulation de Monte-Carlo, qui simule plusieurs résultats pour tester la robustesse de votre plan.",
        "assetNameTooltip": "Un nom unique pour cette catégorie.",
        "assetValueTooltip": "La valeur actuelle dans votre devise.",
        "assetReturnTooltip": "Le rendement annuel attendu de cet actif, après coûts.",
        "assetTaxTooltip": "L'impôt annuel sur le rendement ou la plus-value.",
        "assetStartYearTooltip": "L'année où cette catégorie devient active.",
        "assetEndYearTooltip": "L'année où cette catégorie s'arrête. Laissez vide si non applicable.",
        "assetWithdrawalOrderTooltip": "L'ordre de retrait en cas de déficit ou après la retraite (1 = premier, 99 = dernier).",
        "liabilityNameTooltip": "Un nom unique pour cette catégorie.",
        "liabilityValueTooltip": "La valeur actuelle dans votre devise.",
        "liabilityStartYearTooltip": "L'année où cette catégorie devient active.",
        "liabilityEndYearTooltip": "L'année où cette catégorie s'arrête. Laissez vide si non applicable.",
        "liabilityInterestRateTooltip": "Le taux d'intérêt annuel du prêt. Si vide, la responsabilité diminuera de façon linéaire.",
        "incomeNameTooltip": "Un nom unique pour cette catégorie.",
        "incomeValueTooltip": "La valeur actuelle dans votre devise.",
        "incomeFrequencyTooltip": "La fréquence à laquelle ce revenu se produit.",
        "incomeIndexedTooltip": "Cochez si ce montant doit augmenter annuellement avec l'inflation.",
        "incomeStartYearTooltip": "L'année où cette catégorie devient active.",
        "incomeEndYearTooltip": "L'année où cette catégorie s'arrête. Laissez vide si non applicable.",
        "expenseNameTooltip": "Un nom unique pour cette catégorie.",
        "expenseValueTooltip": "La valeur actuelle dans votre devise.",
        "expenseFrequencyTooltip": "La fréquence à laquelle cette dépense se produit.",
        "expenseIndexedTooltip": "Cochez si ce montant doit augmenter annuellement avec l'inflation.",
        "expenseStartYearTooltip": "L'année où cette catégorie devient active.",
        "expenseEndYearTooltip": "L'année où cette catégorie s'arrête. Laissez vide si non applicable.",
        "languageAlreadySelected": "Cette langue est déjà sélectionnée.",
        "notificationTitle": "Notification",
        "endYearBeforeStartYearError": "L'année de fin ne peut pas être antérieure à l'année de début.",
        "retirementAgeBeforeCurrentAgeError": "L'âge de la retraite ne peut pas être inférieur à l'âge actuel.",
        "autoRebalanceLabel": "Rééquilibrage automatique",
        "autoRebalanceTooltip": "Si cette case est cochée, les pourcentages d'allocation d'actifs seront maintenus tout au long de la simulation en rééquilibrant automatiquement le portefeuille.",
        "portraitModeMessage": "Veuillez tourner votre appareil en mode paysage pour une meilleure expérience.",
        "autoSaveLabel": "Enregistrer automatiquement les données sur cet appareil",
        "autoSaveTooltip": "Lorsqu'il est activé, vos données financières sont automatiquement enregistrées dans le stockage local de votre navigateur. Désactivez-le si vous avez des problèmes de confidentialité.",
        "loadSampleDataButton": "Charger les données d'exemple",
        "total": "Total",
        "sampleDataModalTitle": "Sélectionnez une étape de la vie",
        "recentGraduate": "Jeune diplômé",
        "earlyCareer": "Début de carrière",
        "midCareer": "Milieu de carrière",
        "lateCareer": "Fin de carrière",
        "plansButton": "Plans",
        "actionsButton": "Actions",
        "clearPlanButton": "Effacer le plan",
        "renamePlanButton": "Renommer",
        "duplicatePlanButton": "Dupliquer",
        "deletePlanButton": "Supprimer",
        "onboardingWelcomeTitle": "Bienvenue sur SquirrelPlan!",
        "onboardingIntro": "Découvrez comment de petits changements aujourd'hui peuvent entraîner une croissance significative de votre patrimoine au fil du temps. Cet outil vous aide à projeter votre patrimoine dans le futur. Ajustez votre épargne mensuelle pour voir son impact sur votre projection à 30 ans.",
        "onboardingSliderLabel": "Épargne mensuelle",
        "onboardingStartBlank": "Commencer avec un plan vierge",
        "onboardingNext": "Suivant",
        "onboardingNextButtonExplanation": "Cliquez sur 'Suivant' pour commencer : il vous sera demandé de choisir entre un plan prédéfini ou un plan vierge.",
        "newBlankPlanButton": "Nouveau plan vierge",
        "plansModalTitle": "Choisissez un plan",
        "presetPlansTitle": "Plans prédéfinis",
        "userPlansTitle": "Vos plans",
        "noUserPlans": "Vous n'avez pas encore créé de plans.",
        "onboardingPrevious": "Précédent",
        "projectedWealthLabel": "Richesse projetée",
        "assetDeletionWarning": "Avertissement : Vous avez supprimé un actif ('{assetName}') qui faisait partie de votre allocation d'épargne. Veuillez revoir votre allocation.",
        "enterNewPlanNamePrompt": "Saisissez un nouveau nom pour le plan :",
        "deletePlanConfirmation": "Êtes-vous sûr de vouloir supprimer le plan '{planName}' ?",
        "copyOf": "Copie de ",
        "newPlanName": "Nouveau plan",
        "planNameExistsError": "Un plan avec ce nom existe déjà.",
        "cannotDeleteLastPlanError": "Vous ne pouvez pas supprimer le dernier plan.",
        "savePresetAsNewPlanPrompt": "Vous avez modifié un préréglage. Souhaitez-vous enregistrer vos modifications en tant que nouveau plan ? Veuillez saisir un nom pour le nouveau plan."
    },
    "it": {
        "pageTitle": "SquirrelPlan",
        "languageSelector": "Lingua",
        "navbarBrand": "SquirrelPlan",
        "darkModeLabel": "Modalità oscura",
        "importButton": "Importa",
        "exportButton": "Esporta",
        "clearButton": "Cancella",
        "settingsTitle": "Impostazioni",
        "inflationLabel": "Inflazione (%)",
        "financialDataTitle": "Dati Finanziari",
        "assetsAccordionButton": "Attività",
        "newAssetButton": "Nuova classe di attività",
        "liabilitiesAccordionButton": "Passività",
        "newLiabilityButton": "Nuova classe di passività",
        "incomeAccordionButton": "Reddito",
        "newIncomeButton": "Nuova categoria di reddito",
        "expensesAccordionButton": "Spese",
        "newExpenseButton": "Nuova categoria di spesa",
        "savingsAllocationAccordionButton": "Allocazione dei Risparmi",
        "newAllocationPeriodButton": "Nuovo periodo di allocazione",
        "retirementPlanningAccordionButton": "Pianificazione della Pensione",
        "currentAgeLabel": "Età attuale",
        "legalRetirementAgeLabel": "Età pensionabile legale",
        "monthlyPensionLabel": "Pensione mensile (netta)",
        "withdrawalRateLabel": "Tasso di prelievo (%)",
        "runStandardSimulationButton": "Esegui Simulazione Standard",
        "runMonteCarloSimulationButton": "Esegui Simulazione Monte Carlo",
        "resultsTitle": "Risultati",
        "helpModalTitle": "Aiuto",
        "advancedAccordionButton": "Avanzate",
        "earlyRetirementAgeLabel": "Età di pensionamento anticipato",
        "enableMonteCarloLabel": "Abilita Simulazione Monte Carlo",
        "monteCarloSuccessRateMessage": "Lo scenario attuale ha un tasso di successo del <strong>{successRate}%</strong>.",
        "helpModalWelcome": "Benvenuti in SquirrelPlan!",
        "helpModalSampleData": "Fai clic sul pulsante qui sotto per iniziare caricando alcuni dati di esempio.",
        "helpModalIntro": "Questo strumento gratuito e open source ti aiuta a pianificare e visualizzare il tuo futuro finanziario.",
        "helpModalHowToUse": "Come usare:",
        "helpModalStep1": "<strong>Dati Finanziari:</strong> Inserisci i tuoi attivi (ad es. risparmi, investimenti), passivi (ad es. prestiti), reddito mensile e spese mensili. Per attività e passività, puoi specificare un rendimento annuo o un tasso di interesse. Per reddito e spese, puoi specificare un aumento annuo.",
        "helpModalStep2": "<strong>Allocazione dei Risparmi:</strong> Definisci come vengono allocati i tuoi risparmi in eccesso alle diverse classi di attività. Puoi impostare diverse strategie di allocazione per diversi periodi della tua vita.",
        "helpModalStep3": "<strong>Pianificazione della Pensione:</strong> Inserisci la tua età attuale, l'età pensionabile legale e la tua pensione mensile netta stimata dal governo.",
        "helpModalStep4": "<strong>Impostazioni Avanzate:</strong> Perfeziona la simulazione con parametri come il tasso di inflazione annuo previsto. Puoi also impostare un'età di pensionamento anticipato desiderata e un tasso di prelievo per i tuoi investimenti durante la pensione.",
        "helpModalStep5": "<strong>Esegui Simulazione:</strong><ul><li><strong>Simulazione Standard:</strong> Esegue una singola proiezione basata sui valori esatti forniti.</li><li><strong>Simulazione Monte Carlo:</strong> Abilita questa opzione nella sezione \"Avanzate\" per eseguire centinaia di simulazioni con rendimenti annui casuali per le tue attività. Questo aiuta a valutare la probabilità di raggiungere i tuoi obiettivi finanziari.</li></ul>",
        "helpModalResultsInfo": "I risultati vengono visualizzati in un grafico e in una tabella, mostrando l'evoluzione del tuo patrimonio nel tempo.",
        "helpModalButtonsInfo": "Con i pulsanti in alto a destra, puoi importare o esportare i tuoi dati come file JSON o cancellare tutti i campi.",
        "helpModalPrivacy": "La privacy prima di tutto: non archivieremo né condivideremo mai i tuoi dati in alcun modo.",
        "helpModalSourceCode": "Codice sorgente disponibile su: <a href=\"https://github.com/skapebolt/SquirrelPlan\">https://github.com/skapebolt/SquirrelPlan</a>",
        "nameLabel": "Nome",
        "valueLabel": "Valore",
        "returnLabel": "Rendimento (%)",
        "taxLabel": "Tassa (%)",
        "startLabel": "Inizio",
        "endLabel": "Fine",
        "withdrawalOrderLabel": "Ordine",
        "interestRateLabel": "Tasso di Interesse (%)",
        "frequencyLabel": "Frequenza",
        "indexedLabel": "Indicizzato",
        "monthlyOption": "Mensile",
        "yearlyOption": "Annuale",
        "deleteAssetCategoryLabel": "Elimina categoria di attività",
        "deleteLiabilityCategoryLabel": "Elimina categoria di passività",
        "deleteIncomeCategoryLabel": "Elimina categoria di reddito",
        "deleteExpenseCategoryLabel": "Elimina categoria di spesa",
        "deleteAllocationPeriodLabel": "Elimina periodo di allocazione",
        "startYearLabel": "Anno di inizio",
        "clearDataConfirmation": "Sei sicuro di voler cancellare tutti i dati?",
        "earlyRetirementMessage": "Potresti essere in grado di andare in pensione anticipata nel <strong>{year}</strong> all\'età di <strong>{age}</strong> con un patrimonio netto di <strong>{netWorth}</strong>!",
        "pensionWithdrawalMessage": "Il tuo primo prelievo annuale al raggiungimento dell\'età pensionabile sarebbe di <strong>{amount}</strong> ({rate}% di {netWorth}), o <strong>{monthly}</strong> al mese.",
        "netWorthLabel": "Patrimonio netto",
        "yearHeader": "Anno",
        "ageHeader": "Età",
        "ageLabel": "Età",
        "netIncomeHeader": "Reddito netto",
        "expensesHeader": "Spese",
        "savingsCapacityHeader": "Capacità di risparmio",
        "savingsRateHeader": "Tasso di risparmio",
        "netWorthHeader": "Patrimonio netto",
        "assetHeader": "{asset} (Attività)",
        "liabilityHeader": "{liability} (Passività)",
        "ownHome": "Casa di proprietà",
        "stocks": "Azioni",
        "bonds": "Obbligazioni",
        "savingsAccount": "Conto di risparmio",
        "mortgage": "Mutuo",
        "salary": "Stipendio",
        "livingExpenses": "Spese di sostentamento",
        "mortgageRepayment": "Rimborso del mutuo",
        "bigexpense1": "Spesa Grande 1",
        "bigexpense2": "Spesa Grande 2",
        "bigexpense3": "Spesa Grande 3",
        "inflationTooltip": "L'aumento medio annuo dei prezzi. Viene utilizzato per calcolare il valore futuro del denaro.",
        "currentAgeTooltip": "La tua età attuale in anni.",
        "legalRetirementAgeTooltip": "L\'età in cui inizierai a ricevere la pensione governativa.",
        "monthlyPensionTooltip": "La pensione mensile netta stimata che riceverai dal governo.",
        "withdrawalRateTooltip": "La percentuale del tuo patrimonio totale che prevedi di prelevare annualmente dopo la pensione (ad es. la regola del 4%).",
        "earlyRetirementAgeTooltip": "L\'età in cui prevedi di smettere di lavorare, se precedente all\'età pensionabile legale. Il reddito cesserà, ma la pensione inizierà solo all\'età pensionabile legale.",
        "enableMonteCarloTooltip": "Abilita questa opzione per eseguire una simulazione Monte Carlo, che simula più risultati per testare la robustezza del tuo piano.",
        "assetNameTooltip": "Un nome univoco per questa categoria.",
        "assetValueTooltip": "Il valore corrente nella tua valuta.",
        "assetReturnTooltip": "Il rendimento annuo previsto di questa attività, al netto dei costi.",
        "assetTaxTooltip": "L\'imposta annuale sul rendimento o sulla plusvalenza.",
        "assetStartYearTooltip": "L\'anno in cui questa categoria diventa activa.",
        "assetEndYearTooltip": "L\'anno in cui questa categoria si ferma. Lasciare vuoto se non applicabile.",
        "assetWithdrawalOrderTooltip": "L\'ordine di prelievo in caso di disavanzo o dopo il pensionamento (1 = primo, 99 = ultimo).",
        "liabilityNameTooltip": "Un nome univoco per questa categoria.",
        "liabilityValueTooltip": "Il valore corrente nella tua valuta.",
        "liabilityStartYearTooltip": "L\'anno in cui questa categoria diventa activa.",
        "liabilityEndYearTooltip": "L\'anno in cui questa categoria si ferma. Lasciare vuoto se non applicabile.",
        "liabilityInterestRateTooltip": "Il tasso di interesse annuale del prestito. Se vuoto, la passività diminuirà linearmente.",
        "incomeNameTooltip": "Un nome univoco per questa categoria.",
        "incomeValueTooltip": "Il valore corrente nella tua valuta.",
        "incomeFrequencyTooltip": "Con quale frequenza si verifica questo reddito.",
        "incomeIndexedTooltip": "Controlla se questo importo dovrebbe aumentare annualmente con l\'inflazione.",
        "incomeStartYearTooltip": "L\'anno in cui questa categoria diventa activa.",
        "incomeEndYearTooltip": "L\'anno in cui questa categoria si ferma. Lasciare vuoto se non applicabile.",
        "expenseNameTooltip": "Un nome univoco per questa categoria.",
        "expenseValueTooltip": "Il valore corrente nella tua valuta.",
        "expenseFrequencyTooltip": "Con quale frequenza si verifica questa spesa.",
        "expenseIndexedTooltip": "Controlla se questo importo dovrebbe aumentare annualmente con l\'inflazione.",
        "expenseStartYearTooltip": "L\'anno in cui questa categoria diventa activa.",
        "expenseEndYearTooltip": "L\'anno in cui questa categoria si ferma. Lasciare vuoto se non applicabile.",
        "languageAlreadySelected": "Questa lingua è già selezionata.",
        "notificationTitle": "Notifica",
        "endYearBeforeStartYearError": "L\'anno di fine non può essere precedente all\'anno di inizio.",
        "retirementAgeBeforeCurrentAgeError": "L\'età pensionabile non può essere inferiore all\'età attuale.",
        "autoRebalanceLabel": "Ribilanciamento automatico",
        "autoRebalanceTooltip": "Se selezionato, le percentuali di allocazione degli asset verranno mantenute durante la simulazione ribilanciando automaticamente il portafoglio.",
        "portraitModeMessage": "Per favore, ruota il tuo dispositivo in modalità orizzontale per la migliore esperienza.",
        "autoSaveLabel": "Salva automaticamente i dati su questo dispositivo",
        "autoSaveTooltip": "Quando abilitato, i tuoi dati finanziari vengono salvati automaticamente nella memoria locale del tuo browser. Disabilitalo se hai problemi di privacy.",
        "loadSampleDataButton": "Carica dati di esempio",
        "total": "Totale",
        "sampleDataModalTitle": "Seleziona una fase della vita",
        "recentGraduate": "Neolaureato",
        "earlyCareer": "Inizio carriera",
        "midCareer": "Metà carriera",
        "lateCareer": "Fine carriera",
        "plansButton": "Piani",
        "actionsButton": "Azioni",
        "clearPlanButton": "Cancella piano",
        "renamePlanButton": "Rinomina",
        "duplicatePlanButton": "Duplica",
        "deletePlanButton": "Elimina",
        "onboardingWelcomeTitle": "Benvenuti in SquirrelPlan!",
        "onboardingIntro": "Scopri come piccoli cambiamenti oggi possono portare a una significativa crescita del patrimonio nel tempo. Questo strumento ti aiuta a proiettare la tua ricchezza nel futuro. Regola i tuoi risparmi mensili per vedere come influisce sulla tua proiezione a 30 anni.",
        "onboardingSliderLabel": "Risparmio mensile",
        "onboardingStartBlank": "Inizia con un piano vuoto",
        "onboardingNext": "Seguente",
        "onboardingNextButtonExplanation": "Fai clic su 'Avanti' per iniziare: ti verrà chiesto di scegliere tra un piano preimpostato o uno vuoto.",
        "newBlankPlanButton": "Nuovo piano vuoto",
        "plansModalTitle": "Scegli un piano",
        "presetPlansTitle": "Piani preimpostati",
        "userPlansTitle": "I tuoi piani",
        "noUserPlans": "Non hai ancora creato alcun piano.",
        "onboardingPrevious": "Precedente",
        "projectedWealthLabel": "Ricchezza prevista",
        "assetDeletionWarning": "Attenzione: hai eliminato un asset ('{assetName}') che faceva parte della tua allocazione di risparmio. Rivedi la tua allocazione.",
        "enterNewPlanNamePrompt": "Inserisci un nuovo nome per il piano:",
        "deletePlanConfirmation": "Sei sicuro di voler eliminare il piano '{planName}'?",
        "copyOf": "Copia di ",
        "newPlanName": "Nuovo piano",
        "planNameExistsError": "Esiste già un piano con questo nome.",
        "cannotDeleteLastPlanError": "Non è possibile eliminare l'ultimo piano.",
        "savePresetAsNewPlanPrompt": "Hai modificato un predefinito. Vuoi salvare le modifiche come nuovo piano? Inserisci un nome per il nuovo piano."
    },
    "nl": {
        "pageTitle": "SquirrelPlan",
        "languageSelector": "Taal",
        "navbarBrand": "SquirrelPlan",
        "darkModeLabel": "Donkere modus",
        "importButton": "Importeren",
        "exportButton": "Exporteren",
        "clearButton": "Wissen",
        "settingsTitle": "Instellingen",
        "inflationLabel": "Inflatie (%)",
        "financialDataTitle": "Financiële Gegevens",
        "assetsAccordionButton": "Activa",
        "newAssetButton": "Nieuwe activaklasse",
        "liabilitiesAccordionButton": "Passiva",
        "newLiabilityButton": "Nieuwe passivaklasse",
        "incomeAccordionButton": "Inkomen",
        "newIncomeButton": "Nieuwe inkomenscategorie",
        "expensesAccordionButton": "Uitgaven",
        "newExpenseButton": "Nieuwe uitgavencategorie",
        "savingsAllocationAccordionButton": "Spaarallocatie",
        "newAllocationPeriodButton": "Nieuwe allocatieperiode",
        "retirementPlanningAccordionButton": "Pensioen Planning",
        "currentAgeLabel": "Huidige leeftijd",
        "legalRetirementAgeLabel": "Wettelijke pensioenleeftijd",
        "monthlyPensionLabel": "Maandelijks pensioen (netto)",
        "withdrawalRateLabel": "Opnamepercentage (%)",
        "runStandardSimulationButton": "Standaard Simulatie uitvoeren",
        "runMonteCarloSimulationButton": "Monte Carlo Simulatie uitvoeren",
        "resultsTitle": "Resultaten",
        "helpModalTitle": "Hulp",
        "advancedAccordionButton": "Geavanceerd",
        "earlyRetirementAgeLabel": "Vervroegde pensioenleeftijd",
        "enableMonteCarloLabel": "Monte Carlo Simulatie inschakelen",
        "monteCarloSuccessRateMessage": "Het huidige scenario heeft een slaagkans van <strong>{successRate}%</strong>.",
        "helpModalWelcome": "Welkom bij SquirrelPlan!",
        "helpModalSampleData": "Klik op de onderstaande knop om aan de slag te gaan door enkele voorbeeldgegevens te laden.",
        "helpModalIntro": "Deze gratis en open source tool helpt u uw financiële toekomst te plannen en te visualiseren.",
        "helpModalHowToUse": "Hoe te gebruiken:",
        "helpModalStep1": "<strong>Financiële Gegevens:</strong> Vul uw activa (bv. spaargeld, beleggingen), passiva (bv. leningen), maandelijks inkomen en maandelijkse uitgaven in. Voor activa en passiva kunt u een jaarlijks rendement of rentepercentage opgeven. Voor inkomen en uitgaven kunt u een jaarlijkse stijging opgeven.",
        "helpModalStep2": "<strong>Spaarallocatie:</strong> Bepaal hoe uw overtollige spaargeld wordt toegewezen aan uw verschillende activaklassen. U kunt verschillende allocatiestrategieën instellen voor verschillende perioden in uw leven.",
        "helpModalStep3": "<strong>Pensioenplanning:</strong> Voer uw huidige leeftijd, de wettelijke pensioenleeftijd en uw geschatte netto maandelijkse pensioen van de overheid in.",
        "helpModalStep4": "<strong>Geavanceerde Instellingen:</strong> Verfijn de simulatie met parameters zoals het verwachte jaarlijkse inflatiepercentage. U kunt ook een gewenste vervroegde pensioenleeftijd en een opnamepercentage voor uw beleggingen tijdens uw pensioen instellen.",
        "helpModalStep5": "<strong>Simulatie Uitvoeren:</strong><ul><li><strong>Standaard Simulatie:</strong> Voert een enkele projectie uit op basis van de exacte waarden die u hebt opgegeven.</li><li><strong>Monte Carlo Simulatie:</strong> Schakel dit in de sectie \"Geavanceerd\" in om honderden simulaties uit te voeren met gerandomiseerde jaarlijkse rendementen voor uw activa. Dit helpt om de waarschijnlijkheid van het bereiken van uw financiële doelen te beoordelen.</li></ul>",
        "helpModalResultsInfo": "De resultaten worden weergegeven in een grafiek en een tabel, die de evolutie van uw vermogen in de tijd tonen.",
        "helpModalButtonsInfo": "Met de knoppen rechtsboven kunt u uw gegevens importeren of exporteren als een JSON-bestand, of alle velden wissen.",
        "helpModalPrivacy": "Privacy voorop: we zullen uw gegevens nooit opslaan of delen, in welke vorm dan ook.",
        "helpModalSourceCode": "Broncode beschikbaar op: <a href=\"https://github.com/skapebolt/SquirrelPlan\">https://github.com/skapebolt/SquirrelPlan</a>",
        "nameLabel": "Naam",
        "valueLabel": "Waarde",
        "returnLabel": "Rendement (%)",
        "taxLabel": "Belasting (%)",
        "startLabel": "Start",
        "endLabel": "Einde",
        "withdrawalOrderLabel": "Volgorde",
        "interestRateLabel": "Interestvoet (%)",
        "frequencyLabel": "Frequentie",
        "indexedLabel": "Geïndexeerd",
        "monthlyOption": "Maandelijks",
        "yearlyOption": "Jaarlijks",
        "deleteAssetCategoryLabel": "Activaklasse verwijderen",
        "deleteLiabilityCategoryLabel": "Passiviteitsklasse verwijderen",
        "deleteIncomeCategoryLabel": "Inkomenscategorie verwijderen",
        "deleteExpenseCategoryLabel": "Uitgavencategorie verwijderen",
        "deleteAllocationPeriodLabel": "Allocatieperiode verwijderen",
        "startYearLabel": "Startjaar",
        "clearDataConfirmation": "Weet u zeker dat u alle gegevens wilt wissen?",
        "earlyRetirementMessage": "U kunt mogelijk vervroegd met pensioen in <strong>{year}</strong> op <strong>{age}</strong>-jarige leeftijd met een netto vermogen van <strong>{netWorth}</strong>!",
        "pensionWithdrawalMessage": "Uw eerste jaarlijkse opname bij het bereiken van de pensioenleeftijd zou <strong>{amount}</strong> ({rate}% van {netWorth}) zijn, of <strong>{monthly}</strong> per maand.",
        "netWorthLabel": "Netto vermogen",
        "yearHeader": "Jaar",
        "ageHeader": "Leeftijd",
        "ageLabel": "Leeftijd",
        "netIncomeHeader": "Netto inkomen",
        "expensesHeader": "Uitgaven",
        "savingsCapacityHeader": "Spaarcapaciteit",
        "savingsRateHeader": "Spaargraad",
        "netWorthHeader": "Netto vermogen",
        "assetHeader": "{asset} (Activa)",
        "liabilityHeader": "{liability} (Passiva)",
        "ownHome": "Eigen Woning",
        "stocks": "Aandelen",
        "bonds": "Obligaties",
        "savingsAccount": "Spaarrekening",
        "mortgage": "Hypotheek",
        "salary": "Salaris",
        "livingExpenses": "Levenskosten",
        "mortgageRepayment": "Aflossing hypotheek",
        "bigexpense1": "Grote Uitgave 1",
        "bigexpense2": "Grote Uitgave 2",
        "bigexpense3": "Grote Uitgave 3",
        "inflationTooltip": "De gemiddelde jaarlijkse prijsstijging. Dit wordt gebruikt om de toekomstige waarde van geld te berekenen.",
        "currentAgeTooltip": "Uw huidige leeftijd in jaren.",
        "legalRetirementAgeTooltip": "De leeftijd waarop u een overheidspensioen zult ontvangen.",
        "monthlyPensionTooltip": "Het geschatte netto maandelijkse pensioen dat u van de overheid zult ontvangen.",
        "withdrawalRateTooltip": "Het percentage van uw totale vermogen dat u jaarlijks na uw pensionering van plan bent op te nemen (bijv. de 4%-regel).",
        "earlyRetirementAgeTooltip": "De leeftijd waarop u van plan bent te stoppen met werken, indien eerder dan de wettelijke pensioenleeftijd. Het inkomen stopt, maar het pensioen gaat pas in op de wettelijke pensioenleeftijd.",
        "enableMonteCarloTooltip": "Schakel dit in om een Monte Carlo-simulatie uit te voeren, die meerdere uitkomsten simuleert om de robuustheid van uw plan te testen.",
        "assetNameTooltip": "Een unieke naam voor deze categorie.",
        "assetValueTooltip": "De huidige waarde in uw valuta.",
        "assetReturnTooltip": "Het verwachte jaarlijkse rendement op dit activum, na kosten.",
        "assetTaxTooltip": "De jaarlijkse belasting op het rendement of de vermogenswinst.",
        "assetStartYearTooltip": "Het jaar waarin deze categorie actief wordt.",
        "assetEndYearTooltip": "Het jaar waarin deze categorie stopt. Laat leeg indien niet van toepassing.",
        "assetWithdrawalOrderTooltip": "De opnamevolgorde in geval van een tekort of na pensionering (1 = eerst, 99 = laatst).",
        "liabilityNameTooltip": "Een unieke naam voor deze categorie.",
        "liabilityValueTooltip": "De huidige waarde in uw valuta.",
        "liabilityStartYearTooltip": "Het jaar waarin deze categorie actief wordt.",
        "liabilityEndYearTooltip": "Het jaar waarin deze categorie stopt. Laat leeg indien niet van toepassing.",
        "liabilityInterestRateTooltip": "Het jaarlijkse rentepercentage van de lening. Indien leeg, zal de schuld lineair afnemen.",
        "incomeNameTooltip": "Een unieke naam voor deze categorie.",
        "incomeValueTooltip": "De huidige waarde in uw valuta.",
        "incomeFrequencyTooltip": "Hoe vaak dit inkomen voorkomt.",
        "incomeIndexedTooltip": "Vink aan als dit bedrag jaarlijks met de inflatie moet stijgen.",
        "incomeStartYearTooltip": "Het jaar waarin deze categorie actief wordt.",
        "incomeEndYearTooltip": "Het jaar waarin deze categorie stopt. Laat leeg indien niet van toepassing.",
        "expenseNameTooltip": "Een unieke naam voor deze categorie.",
        "expenseValueTooltip": "De huidige waarde in uw valuta.",
        "expenseFrequencyTooltip": "Hoe vaak deze uitgave voorkomt.",
        "expenseIndexedTooltip": "Vink aan als dit bedrag jaarlijks met de inflatie moet stijgen.",
        "expenseStartYearTooltip": "Het jaar waarin deze categorie actief wordt.",
        "expenseEndYearTooltip": "Het jaar waarin deze categorie stopt. Laat leeg indien niet van toepassing.",
        "languageAlreadySelected": "Deze taal is al geselecteerd.",
        "notificationTitle": "Melding",
        "endYearBeforeStartYearError": "Eindjaar kan niet vóór startjaar liggen.",
        "retirementAgeBeforeCurrentAgeError": "Pensioenleeftijd kan niet lager zijn dan huidige leeftijd.",
        "autoRebalanceLabel": "Automatisch herbalanceren",
        "autoRebalanceTooltip": "Indien aangevinkt, blijven de percentages van de activaspreiding gedurende de simulatie behouden door de portefeuille automatisch te herbalanceren.",
        "portraitModeMessage": "Draai uw toestel naar de landschapsmodus voor de beste ervaring.",
        "autoSaveLabel": "Gegevens automatisch opslaan op dit apparaat",
        "autoSaveTooltip": "Indien ingeschakeld, worden uw financiële gegevens automatisch opgeslagen in de lokale opslag van uw browser. Schakel dit uit als u zich zorgen maakt over uw privacy.",
        "loadSampleDataButton": "Voorbeeldgegevens laden",
        "total": "Totaal",
        "sampleDataModalTitle": "Selecteer een levensfase",
        "plansButton": "Plannen",
        "actionsButton": "Acties",
        "clearPlanButton": "Plan wissen",
        "renamePlanButton": "Hernoemen",
        "duplicatePlanButton": "Dupliceren",
        "deletePlanButton": "Verwijderen",
        "onboardingWelcomeTitle": "Welkom bij SquirrelPlan!",
        "onboardingIntro": "Ontdek hoe kleine veranderingen vandaag kunnen leiden tot aanzienlijke vermogensgroei in de loop van de tijd. Deze tool helpt u uw vermogen in de toekomst te projecteren. Pas uw maandelijkse besparingen aan om te zien hoe dit uw 30-jarenprojectie beïnvloedt.",
        "onboardingSliderLabel": "Maandelijkse besparingen",
        "onboardingStartBlank": "Begin met een leeg plan",
        "onboardingNext": "Volgende",
        "onboardingNextButtonExplanation": "Klik op 'Volgende' om te beginnen: u wordt gevraagd te kiezen tussen een vooraf ingesteld plan of een leeg plan.",
        "plansModalTitle": "Kies een plan",
        "presetPlansTitle": "Vooraf ingestelde plannen",
        "userPlansTitle": "Uw plannen",
        "onboardingPrevious": "Vorige",
        "projectedWealthLabel": "Geprojecteerd vermogen",
        "assetDeletionWarning": "Waarschuwing: U hebt een activum ('{assetName}') verwijderd dat deel uitmaakte van uw spaartoewijzing. Controleer uw toewijzing.",
        "enterNewPlanNamePrompt": "Voer een nieuwe naam in voor het plan:",
        "deletePlanConfirmation": "Weet u zeker dat u het plan '{planName}' wilt verwijderen?",
        "copyOf": "Kopie van ",
        "newPlanName": "Nieuw plan",
        "planNameExistsError": "Er bestaat al een plan met deze naam.",
        "cannotDeleteLastPlanError": "U kunt het laatste plan niet verwijderen.",
        "savePresetAsNewPlanPrompt": "U heeft een voorinstelling bewerkt. Wilt u uw wijzigingen opslaan als een nieuw plan? Voer een naam in voor het nieuwe plan.",
        "recentGraduate": "Recent afgestudeerd",
        "earlyCareer": "Vroege carrière",
        "midCareer": "Midden carrière",
        "lateCareer": "Late carrière",
        "noUserPlans": "U heeft nog geen plannen gemaakt.",
        "newBlankPlanButton": "Nieuw leeg plan"
    },
    "pt": {
        "pageTitle": "SquirrelPlan",
        "languageSelector": "Idioma",
        "navbarBrand": "SquirrelPlan",
        "darkModeLabel": "Modo escuro",
        "importButton": "Importar",
        "exportButton": "Exportar",
        "clearButton": "Limpar",
        "settingsTitle": "Configurações",
        "inflationLabel": "Inflação (%)",
        "financialDataTitle": "Dados Financeiros",
        "assetsAccordionButton": "Ativos",
        "newAssetButton": "Nova classe de ativos",
        "liabilitiesAccordionButton": "Passivos",
        "newLiabilityButton": "Nova classe de passivos",
        "incomeAccordionButton": "Renda",
        "newIncomeButton": "Nova categoria de renda",
        "expensesAccordionButton": "Despesas",
        "newExpenseButton": "Nova categoria de despesa",
        "savingsAllocationAccordionButton": "Alocação de Poupança",
        "newAllocationPeriodButton": "Novo período de alocação",
        "retirementPlanningAccordionButton": "Planejamento de Aposentadoria",
        "currentAgeLabel": "Idade atual",
        "legalRetirementAgeLabel": "Idade legal de aposentadoria",
        "monthlyPensionLabel": "Pensão mensal (líquida)",
        "withdrawalRateLabel": "Taxa de retirada (%)",
        "runStandardSimulationButton": "Executar Simulação Padrão",
        "runMonteCarloSimulationButton": "Executar Simulação Monte Carlo",
        "resultsTitle": "Resultados",
        "helpModalTitle": "Ajuda",
        "advancedAccordionButton": "Avançado",
        "earlyRetirementAgeLabel": "Idade de aposentadoria antecipada",
        "enableMonteCarloLabel": "Ativar Simulação Monte Carlo",
        "monteCarloSuccessRateMessage": "O cenário atual tem uma taxa de sucesso de <strong>{successRate}%</strong>.",
        "helpModalWelcome": "Bem-vindo ao SquirrelPlan!",
        "helpModalSampleData": "Clique no botão abaixo para começar carregando alguns dados de exemplo.",
        "helpModalIntro": "Esta ferramenta gratuita e de código aberto ajuda você a planejar e visualizar seu futuro financeiro.",
        "helpModalHowToUse": "Como usar:",
        "helpModalStep1": "<strong>Dados Financeiros:</strong> Preencha os seus ativos (por exemplo, poupanças, investimentos), passivos (por exemplo, empréstimos), rendimento mensal e despesas mensais. Para ativos e passivos, pode especificar um retorno anual ou taxa de juro. Para rendimentos e despesas, pode especificar um aumento anual.",
        "helpModalStep2": "<strong>Alocação de Poupança:</strong> Defina como as suas poupanças excedentes são alocadas às suas diferentes classes de ativos. Pode configurar diferentes estratégias de alocação para diferentes períodos da sua vida.",
        "helpModalStep3": "<strong>Planeamento de Reforma:</strong> Introduza a sua idade atual, a idade legal de reforma e a sua pensão mensal líquida estimada do governo.",
        "helpModalStep4": "<strong>Definições Avançadas:</strong> Afine a simulação com parâmetros como a taxa de inflação anual esperada. Pode também definir uma idade de reforma antecipada desejada e uma taxa de levantamento para os seus investimentos durante a reforma.",
        "helpModalStep5": "<strong>Executar Simulação:</strong><ul><li><strong>Simulação Padrão:</strong> Executa uma única projeção com base nos valores exatos que forneceu.</li><li><strong>Simulação Monte Carlo:</strong> Ative esta opção na secção \"Avançado\" para executar centenas de simulações com retornos anuais aleatórios para os seus ativos. Isto ajuda a avaliar a probabilitade de atingir os seus objetivos financeiros.</li></ul>",
        "helpModalResultsInfo": "Os resultados são apresentados num gráfico e numa tabela, mostrando a evolução do seu património ao longo do tempo.",
        "helpModalButtonsInfo": "Com os botões no canto superior direito, pode importar ou exportar os seus dados como um ficheiro JSON, ou limpar todos os campos.",
        "helpModalPrivacy": "Privacidade em primeiro lugar: nunca armazenaremos ou compartilharemos seus dados de forma alguma.",
        "helpModalSourceCode": "Código-fonte disponível em: <a href=\"https://github.com/skapebolt/SquirrelPlan\">https://github.com/skapebolt/SquirrelPlan</a>",
        "nameLabel": "Nome",
        "valueLabel": "Valor",
        "returnLabel": "Retorno (%)",
        "taxLabel": "Imposto (%)",
        "startLabel": "Início",
        "endLabel": "Fim",
        "withdrawalOrderLabel": "Ordem",
        "interestRateLabel": "Taxa de Juros (%)",
        "frequencyLabel": "Frequência",
        "indexedLabel": "Indexado",
        "monthlyOption": "Mensal",
        "yearlyOption": "Anual",
        "deleteAssetCategoryLabel": "Excluir categoria de ativo",
        "deleteLiabilityCategoryLabel": "Excluir categoria de passivo",
        "deleteIncomeCategoryLabel": "Excluir categoria de renda",
        "deleteExpenseCategoryLabel": "Excluir categoria de despesa",
        "deleteAllocationPeriodLabel": "Excluir período de alocação",
        "startYearLabel": "Ano de início",
        "clearDataConfirmation": "Tem certeza de que deseja limpar todos os dados?",
        "earlyRetirementMessage": "Você pode conseguir se aposentar mais cedo em <strong>{year}</strong> aos <strong>{age}</strong> anos com um patrimônio líquido de <strong>{netWorth}</strong>!",
        "pensionWithdrawalMessage": "Sua primeira retirada anual ao atingir a idade de aposentadoria seria de <strong>{amount}</strong> ({rate}% de {netWorth}), ou <strong>{monthly}</strong> por mês.",
        "netWorthLabel": "Patrimônio líquido",
        "yearHeader": "Ano",
        "ageHeader": "Idade",
        "ageLabel": "Idade",
        "netIncomeHeader": "Renda líquida",
        "expensesHeader": "Despesas",
        "savingsCapacityHeader": "Capacidade de poupança",
        "savingsRateHeader": "Taxa de poupança",
        "netWorthHeader": "Patrimônio líquido",
        "assetHeader": "{asset} (Ativo)",
        "liabilityHeader": "{liability} (Passivo)",
        "ownHome": "Casa própria",
        "stocks": "Ações",
        "bonds": "Títulos",
        "savingsAccount": "Conta poupança",
        "mortgage": "Hipoteca",
        "salary": "Salário",
        "livingExpenses": "Despesas de subsistência",
        "mortgageRepayment": "Pagamento da hipoteca",
        "bigexpense1": "Despesa Grande 1",
        "bigexpense2": "Despesa Grande 2",
        "bigexpense3": "Despesa Grande 3",
        "inflationTooltip": "O aumento médio anual dos preços. É usado para calcular o valor futuro do dinheiro.",
        "currentAgeTooltip": "Sua idade atual em anos.",
        "legalRetirementAgeTooltip": "A idade em que você começará a receber a pensão do governo.",
        "monthlyPensionTooltip": "A pensão mensal líquida estimada que você receberá do governo.",
        "withdrawalRateTooltip": "A porcentagem de seus ativos totais que você planeja retirar anualmente após a aposentadoria (por exemplo, a regra dos 4%).",
        "earlyRetirementAgeTooltip": "A idade em que você planeja parar de trabalhar, se for antes da idade legal de aposentadoria. A renda irá parar, mas a pensão só começará na idade legal de aposentadoria.",
        "enableMonteCarloTooltip": "Ative para executar uma simulação de Monte Carlo, que simula múltiplos resultados para testar a robustez do seu plano.",
        "assetNameTooltip": "Um nome exclusivo para esta categoria.",
        "assetValueTooltip": "O valor atual em sua moeda.",
        "assetReturnTooltip": "O retorno anual esperado deste ativo, após os custos.",
        "assetTaxTooltip": "O imposto anual sobre o retorno ou ganho de capital.",
        "assetStartYearTooltip": "O ano em que esta categoria se torna ativa.",
        "assetEndYearTooltip": "O ano em que esta categoria para. Deixe em branco se não for aplicável.",
        "assetWithdrawalOrderTooltip": "A ordem de retirada em caso de déficit ou após a aposentadoria (1 = primeiro, 99 = último).",
        "liabilityNameTooltip": "Um nome exclusivo para esta categoria.",
        "liabilityValueTooltip": "O valor atual em sua moeda.",
        "liabilityStartYearTooltip": "O ano em que esta categoria se torna ativa.",
        "liabilityEndYearTooltip": "O ano em que esta categoria para. Deixe em branco se não for aplicável.",
        "liabilityInterestRateTooltip": "A taxa de juros anual do empréstimo. Se estiver em branco, a responsabilidade diminuirá linearmente.",
        "incomeNameTooltip": "Um nome exclusivo para esta categoria.",
        "incomeValueTooltip": "O valor atual em sua moeda.",
        "incomeFrequencyTooltip": "Com que frequência essa renda ocorre.",
        "incomeIndexedTooltip": "Verifique se este valor deve aumentar anualmente com a inflação.",
        "incomeStartYearTooltip": "O ano em que esta categoria se torna ativa.",
        "incomeEndYearTooltip": "O ano em que esta categoria para. Deje em branco se não for aplicável.",
        "expenseNameTooltip": "Um nome exclusivo para esta categoria.",
        "expenseValueTooltip": "O valor atual em sua moeda.",
        "expenseFrequencyTooltip": "Com que frequência essa despesa ocorre.",
        "expenseIndexedTooltip": "Verifique se este valor deve aumentar anualmente com a inflação.",
        "expenseStartYearTooltip": "O ano em que esta categoria se torna ativa.",
        "expenseEndYearTooltip": "O ano em que esta categoria para. Deixe em branco se não for aplicável.",
        "languageAlreadySelected": "Este idioma já está selecionado.",
        "notificationTitle": "Notificação",
        "endYearBeforeStartYearError": "O ano final não pode ser anterior ao ano inicial.",
        "retirementAgeBeforeCurrentAgeError": "A idade de aposentadoria não pode ser menor que a idade atual.",
        "autoRebalanceLabel": "Rebalanceamento automático",
        "autoRebalanceTooltip": "Se marcada, as percentagens de alocação de ativos serão mantidas ao longo da simulação através do rebalanceamento automático da carteira.",
        "portraitModeMessage": "Por favor, vire o seu dispositivo para o modo paisagem para a melhor experiência.",
        "autoSaveLabel": "Salvar dados automaticamente neste dispositivo",
        "autoSaveTooltip": "Quando ativado, seus dados financeiros são salvos automaticamente no armazenamento local do seu navegador. Desative se tiver preocupações com a privacidade.",
        "loadSampleDataButton": "Carregar dados de exemplo",
        "total": "Total",
        "sampleDataModalTitle": "Selecione uma fase da vida",
        "recentGraduate": "Recém-formado",
        "earlyCareer": "Início de carreira",
        "midCareer": "Meio de carreira",
        "lateCareer": "Fim de carreira",
        "plansButton": "Planos",
        "actionsButton": "Ações",
        "clearPlanButton": "Limpar plano",
        "renamePlanButton": "Renomear",
        "duplicatePlanButton": "Duplicar",
        "deletePlanButton": "Excluir",
        "onboardingWelcomeTitle": "Bem-vindo ao SquirrelPlan!",
        "onboardingIntro": "Descubra como pequenas mudanças hoje podem levar a um crescimento significativo de riqueza ao longo do tempo. Esta ferramenta ajuda-o a projetar a sua riqueza para o futuro. Ajuste as suas poupanças mensais para ver como isso afeta a sua projeção a 30 anos.",
        "onboardingSliderLabel": "Poupança mensal",
        "onboardingStartBlank": "Começar com um plano em branco",
        "onboardingNext": "Próximo",
        "onboardingNextButtonExplanation": "Clique em 'Avançar' para começar: você será solicitado a escolher entre um plano predefinido ou um em branco.",
        "newBlankPlanButton": "Novo plano em branco",
        "plansModalTitle": "Escolha um plano",
        "presetPlansTitle": "Planos predefinidos",
        "userPlansTitle": "Os seus planos",
        "noUserPlans": "Ainda não criou nenhum plano.",
        "onboardingPrevious": "Anterior",
        "projectedWealthLabel": "Riqueza projetada",
        "assetDeletionWarning": "Aviso: você excluiu um ativo ('{assetName}') que fazia parte de sua alocação de poupança. Revise sua alocação.",
        "enterNewPlanNamePrompt": "Digite um novo nome para o plano:",
        "deletePlanConfirmation": "Tem certeza de que deseja excluir o plano '{planName}'?",
        "copyOf": "Cópia de ",
        "newPlanName": "Novo Plano",
        "planNameExistsError": "Já existe um plano com este nome.",
        "cannotDeleteLastPlanError": "Você não pode excluir o último plano.",
        "savePresetAsNewPlanPrompt": "Você editou uma predefinição. Deseja salvar suas alterações como um novo plano? Digite um nome para o novo plano."
    },
};

let currentLang = 'en';

async function setLanguage(lang) {
    currentLang = lang;
    document.documentElement.lang = lang;
    
    if (window.SquirrelPlanApp && window.SquirrelPlanApp.saveSettings && window.SquirrelPlanApp.getSettings) {
        const settings = window.SquirrelPlanApp.getSettings();
        settings.language = lang;
        window.SquirrelPlanApp.saveSettings(settings);
    }

    if (!ALL_TRANSLATIONS[lang]) {
        console.error(`Translations for language '${lang}' not found.`);
        if (lang !== 'en' && ALL_TRANSLATIONS['en']) {
            currentLang = 'en';
            document.documentElement.lang = 'en';
        } else {
            return; 
        }
    }

    translatePage();
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang: currentLang } }));
}

function translatePage() {
    const langTranslations = ALL_TRANSLATIONS[currentLang];
    if (!langTranslations) {
        return;
    }

    document.querySelectorAll('[data-i18n-key]').forEach(element => {
        const key = element.getAttribute('data-i18n-key');
        if (langTranslations[key]) {
            const icon = element.querySelector('i.bi');
            element.innerHTML = langTranslations[key];
            if (icon) {
                element.appendChild(document.createTextNode(' '));
                element.appendChild(icon);
            }
        }
    });

    document.querySelectorAll('[data-i18n-title-key]').forEach(element => {
        const key = element.getAttribute('data-i18n-title-key');
        if (langTranslations[key]) {
            element.setAttribute('title', langTranslations[key]);
        }
    });

    if (langTranslations['pageTitle']) {
        document.title = langTranslations['pageTitle'];
    }
}

function getTranslation(key, replacements = {}) {
    const langTranslations = ALL_TRANSLATIONS[currentLang];
    let translation = langTranslations && langTranslations[key] ? langTranslations[key] : key;

    for (const placeholder in replacements) {
        translation = translation.replace(`{${placeholder}}`, replacements[placeholder]);
    }

    return translation;
}

window.getTranslation = getTranslation;

window.addEventListener('languageChanged', (e) => {
    const lang = e.detail.lang;
    const langTranslations = ALL_TRANSLATIONS[lang];
    if (!langTranslations) return;

    const languageSelector = document.getElementById('language-selector');
    if (languageSelector) {
        languageSelector.textContent = langTranslations['languageSelector'] || 'Language';
    }
});
